### ISSUE TITLE
Migrating from benjamminf/craft-neo to spicyweb/craft-neo ?

### ISSUE THREAD

**Issue by Osze** [spicywebau/craft-neo#143] opened 2018-10-31 08:51 UTC
Hi Spicyweb, 

great job with NEO!!

I have worked with benjamminf/craft-neo for a week now - installed it manually by repositories. 

How do I change it to spicyweb/craft-neo without loosing any data? Can I just install the latest Neo version from plugin store and then delete the benjamminf/craft-neo or how should I tackle this?

Thanks again for a great plugin.

**Comment by Osze** [comment] 2018-10-31 11:21
did as you said, and installation went fine but it throws an error when browsing an entry with neo and when browsing the pages using neo.

`Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db-se_db.elements.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
in /srv/users/craft/apps/domain-se/craft/vendor/yiisoft/yii2/db/Command.php at line 1258`

**Comment by 23d1** [comment] 2018-11-01 03:09
I can confirm, getting SQL errors.
`SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'askrembla.elements.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by Reddogdesigns** [comment] 2018-11-01 20:17
I am also receiving this error when upgrading.

**Comment by ttempleton** [comment] 2018-11-02 05:57
Sorry about this.  The issue should be resolved in the latest release, but if any of you continue to experience errors, please let us know.

Good to hear that the installation otherwise went well, though, @Osze 👍

**Closed by ttempleton** 2018-11-02 05:57 UTC

**Comment by 23d1** [comment] 2018-11-04 19:31
Quick question;
How does one update without composer? Is there a table in the DB that one can modify? The production server doesn't have composer, which is a huge bummer—so I've tried to manually update folders and composer.json (which I thought Craft somehow checked regardless of composer, which seems to be wrong). Any help is much appreciated.

Cheers, and great job!

**Comment by ttempleton** [comment] 2018-11-08 11:58
Thanks @23d1!

No database changes would be necessary.  If your production server doesn't have Composer, then I think the best option would be to perform the `composer update` on your dev machine, then copy the `composer.json`/`composer.lock` files and the entire `vendor` directory to the production server.  That should be all you need to do (do keep a backup of the original `composer.json`, `composer.lock`, `vendor` and your database just in case, though).  Try that and let us know how you go.  I'm on leave this week so unfortunately I won't be able to help immediately if there are any issues, but I'll do my best to help with any issues next week once I'm back in the office.
