### ISSUE TITLE
Updating entry w NEO field results in exception "Attempting to duplicate an unsaved element"

### ISSUE THREAD

**Issue by mach1media** [spicywebau/craft-neo#354] opened 2020-05-29 20:22 UTC
#### Description
Updating existing entry with NEO field produces yii exception "Attempting to duplicate an unsaved element."

vendor/craftcms/cms/src/services/Elements.php at line 734

#### Steps to reproduce
1. Create new entry with NEO field and SAVE
2. UPDATE entry with NEO field making one small change to any field
3.

##### Application Info
PHP version	7.3.9
OS version	Darwin 19.5.0
Database driver & version	MySQL 5.7.26
Image driver & version	GD 7.3.9
Craft edition & version	Craft Pro 3.4.21
Yii version	2.0.35
Twig version	2.12.5
Guzzle version	6.5.4
Imagine version	1.2.3-dev

##### Plugins
Config Values Field	1.0.0
Entry Instructions	1.0.7
Freeform	3.6.9
Image Resizer	2.0.9
Matrix Toolbar	1.0.6
Neo	2.7.12
Obfuscator	1.0.4
Position Fieldtype	1.0.14
Redactor	2.6.1
Redactor Tweaks	2.0.4
SEO	3.6.5.1
Super Table	2.4.9
Table Maker	2.0.1
Video Embedder	1.1.4

- Is eager-loading used? YES

**Comment by ttempleton** [comment] 2020-05-30 01:56
Closing this issue as a duplicate of #352.

**Closed by ttempleton** 2020-05-30 01:56 UTC
Labels: duplicate
