### ISSUE TITLE
Uncaught Type-Error in Console Panel after editing content in neo block

### ISSUE THREAD

**Issue by fabianhaef** [spicywebau/craft-neo#540] opened 2022-02-10 10:48 UTC
#### Description
After editing  and saving a redactor-field in a neo module, the block completely disappeared and a javascript error is being thrown in the console. 

![Bildschirmfoto 2022-02-10 um 11 42 10](https://user-images.githubusercontent.com/55360588/153390718-94e1310b-7c0b-4333-a65a-8374621de717.png)

#### Other information
- Neo version: 2.10.8
- Craft version: Craft Pro 3.6.18
- Redactor version: 2.9.1

**Comment by ttempleton** [comment] 2022-02-10 11:00
I'm unable to reproduce this using Craft 3.7.32, Neo 2.12.4 and Redactor 2.9.1 - does updating Craft and Neo resolve the issue?

**Comment by fabianhaef** [comment] 2022-02-10 12:04
Both NEO and Redactor are already on the latest version. My company wants to keep craft on 3.6.18 because we would only update to 3.7 if craft 3.8 is released. Do you might reckon downgrading NEO or Redactor?

**Comment by ttempleton** [comment] 2022-02-11 09:06
There was a similar issue reported for Redactor (craftcms/redactor#359), which I'm assuming is causing this. That will be fixed in the next version of Redactor, or by downgrading to Redactor 2.8.8 until the next version is released.

**Closed by ttempleton** 2022-02-11 09:06 UTC
