### ISSUE TITLE
Duplicate / Missing blocks

### ISSUE THREAD

**Issue by jerwarren** [spicywebau/craft-neo#127] opened 2018-03-20 20:54 UTC
I've been working on a rather large site that uses neo pretty extensively, and as I've been inputting content I've been running into what I believed to be the 1.5.0 "missing blocks" problem.  I THINK I've downgraded to 1.4.1 (but the version number still says 1.5.0) so I'm not 100% sure this is the problem I'm now running into, but I think it might be.

What happens:

I have two neo blocks in one section.  When I add stuff to each of these neo blocks and save, all looks well.  But If I edit it again later and add a new block to one of them, I end up with duplicates of other blocks in the output.  But if I go in to edit the blocks again, the duplicates don't show up.

Then later, when adding another block to the other neo in the section, the duplicates show up in the first one in the editor.

If I then delete them, all looks well.

But then later if I make another change I sometimes end up with 3 of that same duplicate block.

Does this sound like the 1.5.0 problem, and/or what is the best way to ACTUALLY downgrade?  The latest commit says "removing 1.5.0" but I'm not 100% confident that it actually represents 1.4.1...

**Comment by jerwarren** [comment] 2018-03-21 18:05
turning off "save only edited blocks" seems to have solved this.

**Comment by jerwarren** [comment] 2018-03-31 01:14
False alarm.  I can't figure out when and how this is going wrong.  It seems to be breaking when loading the entry into the editor.  I can save it and all looks well, but then when returning to edit it again later is when everything falls apart.

**Comment by jerwarren** [comment] 2018-04-11 22:26
I finally realized there's a 'Releases' page on this github, where I grabbed 1.4.1 and all is well now.

**Comment by peterbedor** [comment] 2018-09-12 22:01
We're having a somewhat similar issue where, seemingly randomly, every Neo block will duplicate itself four times.  This duplication exists in the CP as well as the template output.  Deleting this duplicate blocks doesn't work and there is no error output.

**Comment by pierrestoffe** [comment] 2018-09-28 21:33
I've noticed the same issue and it seems to only happen to entries where we use drafts.

**Comment by ttempleton** [comment] 2018-11-22 08:05
Closing this issue as a duplicate of #120 which will be fixed by the end of the year.

**Closed by ttempleton** 2018-11-22 08:05 UTC
Labels: bug, duplicate
