### ISSUE TITLE
Neo field doesn't get saved when editing an entry field containing the neo field

### ISSUE THREAD

**Issue by wei2go** [spicywebau/craft-neo#369] opened 2020-06-18 03:32 UTC
#### Description

- I have an entry and let's call it "Parent".
- "Parent" has an entry field called "Children", which is set to the entries in "Children" section.
- "Children" section has a Neo field, and also other types of field which comes with Craft.
- On this "Parent" entry, I already have one entry set for the "Children" field, let's call it "Child A".

- Now when I edit the "Parent", I double click "Child A" on the "Children" field, trying to edit the fields of "Child A".
- Whatever the changes I try to make to the Neo field are not saved after I try to save "Child A". All other types of fields of Child A are saved correctly.

I've been using Neo for a few years since Craft 2. I believe this is a new issue as I don't remember it happening before?

#### Steps to reproduce
See description above.

#### Other information
- Neo version: 2.7.17
- Craft version: Craft Pro 3.4.24
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: N/A
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: N/A
- Is eager-loading used? N/A

**Comment by ttempleton** [comment] 2020-06-18 10:48
Thanks for reporting this, @wei2go; this was being caused by the blocks' sort order not being set properly in element editor modals, and it has now been fixed in Neo 2.7.18.

**Closed by ttempleton** 2020-06-18 10:48 UTC
Labels: bug
