### ISSUE TITLE
Trouble with neo fields while running through Codeception

### ISSUE THREAD

**Issue by khamer** [spicywebau/craft-neo#538] opened 2022-02-08 16:00 UTC
#### Description

I'm running into an issue where neo fields don't seem to populate while trying to run through Codeception. I've dug into this but haven't nailed down the exact issue; any ideas or help would be most appreciated.

#### Steps to reproduce
There's an example repo you should be able to use to replicate the issue here: https://github.com/khamer/craftdemo-custom-fields-with-codeception

You should be able to configure that to run locally based on your development environments. If all is well, you should be able to run the codeception functional test ExampleCest and see "Test redactor in matrix" work but "Test redactor in neo" fail.

Having dug into this for a while, I believe the value isn't even being populated into the Entry even before it's saved. I think that's happening because it looks like for that to work, the generated tests/_craft/storage/runtime/compiled_classes/CustomFieldBehavior_***********.php file would need to have a reference to the relevant neo field - in this case, `neoContent` - but I only see `bodyContent` in the generated file. I _think_ at the time of generating this file, for whatever reason the neo fields aren't within the fields table yet; and that's as far I've gotten.

It doesn't seem to be an issue for Matrix fields or the craftcms/redactor plugin's fields. I'll ask the Pixel & Tonic guys too, but I'd love to get this solved because this blocks us being able to do automated testing on sites using Neo.

#### Other information
- Neo version: 2.12.4
- Craft version: 3.7.30.1
- Is eager-loading used? I don't think it comes into play here.

**Comment by ttempleton** [comment] 2022-02-09 03:11
Based on the example test, as well as the `blocks` array, the `sortOrder` array would also need to be set for it to save properly.

If you're saving a new entry with only one Neo block and you don't need to test anything related to `sortOrder`, then the more simplified type of block array in the style of the Matrix test should work as well. Something similar to what you originally posted in #535, but using the block type handle instead of its ID (I guess the example I posted in reply was overdoing it a little for a case of saving one block 😅).

Also, you shouldn't need to set the `modified` state of the block, as it's no longer used and will be removed in the future.

Let me know if you have any other questions!

**Comment by khamer** [comment] 2022-02-09 14:08
@ttempleton I updated the repo, even with those changes the test fails. I'm pretty certain there's some timing issue with the neo plugin (or within Craft / CustomFieldBehavior?) where the field type isn't totally setup by the time it's being populated.

**Comment by ttempleton** [comment] 2022-02-10 06:31
I installed Super Table and added a test for that, which also fails, so I'm assuming the issue is on Craft's end, since there's nothing unusual [Neo](https://github.com/spicywebau/craft-neo/blob/25719c1656bc83626e0f98e28710c3ccc1912a46/src/Plugin.php#L102) or [Super Table](https://github.com/verbb/super-table/blob/aeb50ce534e2a5200c50e69a3d591c12d182a572/src/SuperTable.php#L93) are doing when registering the field type that would cause them not to be set up in time.

**Comment by ttempleton** [comment] 2022-02-10 09:57
Please disregard my previous comment, there was a mistake in the Super Table test and it does pass after being corrected.

That said, I don't think this is a Neo bug; I've tried adding Neo content via the content migration that adds the blog entries when the tests run, which didn't work, but applying the same content migration using `./craft migrate/up` does add the Neo content. There isn't anything Neo would be doing differently between the two cases that would cause it to work for one and not the other, so I agree with you that there must be a timing issue over when Neo tries to save its content vs. when the database contents have been reapplied during the tests, which I'm not sure Neo can do anything about, unfortunately.

**Comment by khamer** [comment] 2022-02-10 13:59
I realy appreciate the digging. When I first encountered the issue, it seems to only be true when Codeception was configured `dbSetup: { clean: true, setupCraft: true }` but not when `dbSetup: { clean: false, setupCraft: false }`. When I made this separate repo to try to replicate the bug in a more controlled environment, it seems to fail either way.

It might be Craft's bug, but I assume there must be something different Neo is doing that SuperTable and Redactor aren't doing that is causing Neo to fail. Does it make any sense for this to be related to the customFieldBehavior generated class, or does that sound like the wrong thread to pull? I also have an [open issue](https://github.com/craftcms/craft/issues/76) I'll follow up on with Pixel & Tonic.

**Comment by ttempleton** [comment] 2022-02-11 12:40
Hmm, I just tried running the tests a few times with `dbSetup: { clean: false, setupCraft: false }` and both the Matrix and Neo tests passed. When setting it back to `dbSetup: { clean: true, setupCraft: true }` the Neo test fails again but there are no references to any custom fields in the generated `CustomFieldBehavior` class. I'm guessing that isn't related if the Matrix test is still passing, though.

I've looked into what's happening at the moment the Neo test goes wrong, and it looked like the Neo blocks weren't being saved because they were determined to have an invalid block type, because the query Neo does for block types at that point returned no results. I tried querying for Matrix block types instead of Neo, and that also returned no results. I can't really explain that, since the Matrix test runs first, doing the same check for block types which works (and trying to query for Neo block types instead *does* return results). At this stage I'm not seeing anything obvious that Neo could be doing differently to cause that, but I'll keep looking into it.

**Comment by ttempleton** [comment] 2022-06-24 15:31
As I've just mentioned in the related Craft issue, this turned out to be a Neo bug. It was happening due to the memoized array of Neo block types by field ID being set to an empty array (presumably at some point during the tests before the block type table had actually been populated), and since Neo was only checking that the data for a given field ID had been set - and assuming that it being set meant it actually contained any block types - this led to Neo not finding the block types the blocks belonged to, and therefore deciding that the blocks were invalid.

This will be fixed in the next release, which should be sometime next week. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `2.x-dev as 2.13.11`.

**Comment by khamer** [comment] 2022-06-24 16:10
Awesome - I'll definitely try this next week, I appreciate you following up.

**Comment by ttempleton** [comment] 2022-06-29 01:35
Just released Neo 2.13.12 which should fix this bug. I'll close the issue now, but please let me know if any other problems come up with it!

**Closed by ttempleton** 2022-06-29 01:35 UTC
Labels: bug
