### ISSUE TITLE
Neo block does not render in a fresh commerce product

### ISSUE THREAD

**Issue by yumpdevs** [spicywebau/craft-neo#912] opened 2024-07-19 00:54 UTC
### Bug Description

When creating a fresh commerce product, the neo field added to that product can't be rendered. 
after clicking the "+ field" button, the system will log a 500 error of "No owner ID assigned to the Neo block".

### Steps to reproduce

- Install craft, commerce (v4.6.3.1), neo
- Add a neo field in commerce product type
- Create a new commerce product (edit url: admin/commerce/products/[productTypeHandle]/new)
- Click "+ neo field" on neo field

### Expected behaviour

After clicking on the "+ neo field" on neo field
You should see the system is trying to call "admin%2Factions%2Fneo%2Finput%2Frender-blocks"
with payload
{
  "namespace": "fields[fieldHandle][blocks]",
  "fieldId": 225,
  "unsavedIds": [],
  "blocks": [
    {
      "collapsed": false,
      "enabled": true,
      "level": 1,
      "ownerId": null,
      "type": 90,
      "prevSiblingId": null,
      "parentId": null
    }
  ]
}

because the ownerId is null, it throws a 500 error with "No owner ID assigned to the Neo block"

### Neo version

4.2.7

### Craft CMS version

4.10.4

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2024-07-19 01:07
This is almost certainly a duplicate of #909 which is fixed in 4.2.8.

**Closed as not planned by ttempleton** 2024-07-19 01:07 UTC
Labels: bug report, duplicate
