### ISSUE TITLE
Lightswitch field disabled until entry save

### ISSUE THREAD

**Issue by eliseferguson** [spicywebau/craft-neo#129] opened 2018-05-11 14:54 UTC
If I add a Neo block that has a lightswitch field to an entry I cannot change the state of that lightswitch.  The entry has to be saved first and then re-edited and then the lightswitch field state can be changed. (craft 2.6.3015)

**Comment by ttempleton** [comment] 2018-11-28 13:44
Closing this issue as a duplicate of #118 (which will be fixed by the end of the week)

**Closed by ttempleton** 2018-11-28 13:44 UTC
Labels: bug, duplicate
