### ISSUE TITLE
Copy issue

### ISSUE THREAD

**Issue by minalove** [spicywebau/craft-neo#452] opened 2021-05-18 03:05 UTC
#### Description
When I try to copy a section or a block it shows an error and hides all contents sections and blocks
![Screen Shot 2021-05-18 at 12 28 11 pm](https://user-images.githubusercontent.com/14028979/118583639-89eea400-b7d4-11eb-9235-abedc575d20e.png)

I'm using the Button Box plugin. Is it possible to make the error?

#### Steps to reproduce
1. Go to an admin page
2. Try to copy a section
3. Can't see content sections or block

#### Other information
- Neo version: 2.9.6
- Craft version:  3.6.12
- (if multi-site) What is the affected Neo field's propagation method: not a multi-site
- Is eager-loading used?  no

**Comment by ttempleton** [comment] 2021-05-21 08:28
I'm unable to reproduce this error when using Button Box fields, the Neo block is able to be copied (though when pasting, for most Button Box fields, the pasted block's field values are overridden by the fields' default values, which is probably the same issue as supercool/buttonbox#38) so I don't think Button Box is causing this error.

If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au and we'll look into it.

**Comment by ttempleton** [comment] 2021-05-28 12:58
Closing this issue in favour of #459.

**Closed by ttempleton** 2021-05-28 12:58 UTC

**Comment by ttempleton** [comment] 2021-06-04 03:38
This should now be fixed in Neo 2.9.11.

**Comment by minalove** [comment] 2021-06-04 04:47
Thank you very much!
