### ISSUE TITLE
When adding a new block, old content is being injected

### ISSUE THREAD

**Issue by chrismlusk** [spicywebau/craft-neo#721] opened 2023-03-13 16:22 UTC
### Bug Description

I have a Neo field on an entry. Let's say a couple of versions ago, this entry had block types `Block A` and `Block B`. Those have since been deleted, and the entry has had no blocks added in this particular Neo field.

Now, months later, when I go to this entry and attempt to add a `Block C` type, the old content from `Block A` gets automatically injected into the new block — like the entire field layout of `Block C` is replaced with the `Block A` layout and the content from the old block.

The top bar of `Block C` still shows the correct block name and handle, but everything in the block body is definitely from an old and different block.

### Steps to reproduce

1. Edit an existing entry that has a Neo field where blocks have been deleted.
2. Add a new (different) block type.
3. The field layout of the newly added block is then replaced with an older block that was deleted.

### Neo version

3.7.0

### Craft CMS version

4.4.1

**Comment by chrismlusk** [comment] 2023-03-13 16:32
Out of curiosity, I just tried to save the entry after having this happen, and I get validation errors because a required field in `Block C` was missing. So, I guess even though it looks like `Block A` is being re-added to the entry, it's not really? 

I exited without saving, and then I tried again with a different block that has no required fields. We'll call it `Block D`. This time, even though the same issue looks to happen, when I save the entry and the page refreshes, I now have a single `Block D` as intended.

This behavior repeats for however many old, deleted blocks there were in this field. 

In the entry I'm testing with, there were only three blocks before. So once I get past that, I can add/edit blocks as expected.

Ghost content?

**Comment by chrismlusk** [comment] 2023-03-13 16:43
Digging further, when I can recreate the issue, I see that the `neo/input/update-visible-elements` action's response in `blocks.new0.tabs` is the old markup from `Block A` that's replacing what should be in `Block C`.

**Comment by ttempleton** [comment] 2023-03-13 22:51
Any chance you're being affected by https://github.com/spicywebau/craft-neo/issues/717#issuecomment-1461939653? Does it work properly after you run `php craft gc/run`?

**Comment by chrismlusk** [comment] 2023-03-14 00:23
Running garbage collection did not do the trick. I'm seeing the same behavior.

**Comment by ttempleton** [comment] 2023-03-14 10:35
Ah whoops, I misread your post, sorry. Garbage collection probably wouldn't resolve this.

I've made some changes to fix another bug affecting the `neo/input/update-visible-elements` action, which I _think_ should fix this as well, though I'm not absolutely sure. Could you please change your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.7.0`, run `composer update` and let me know if that resolves it?

If that doesn't resolve it, then if possible, could you please send in your composer.json/lock and database backup to plugins@spicyweb.com.au, along with letting us know which entry is being affected.

**Comment by ttempleton** [comment] 2023-03-14 19:54
Thanks for sending that through @chrismlusk. It turned out we weren't checking the correct site ID when getting the block data during the `update-visible-elements` action. That should be fixed now for the next release.

I think that fix should also fix #722 - I can check for that if the affected entry for that bug is from the same Craft project? If it's not, could you please let me know if the fix for this issue has fixed that one as well?

**Comment by chrismlusk** [comment] 2023-03-14 20:29
Great! Thanks for the quick fix.

Yes, #722 is from the same Craft project. The particular block where the visibility conditions are set can be found at `Blocks` > `Near Me Row`.

**Comment by andrewmenich** [comment] 2023-03-16 15:51
Hi there, it looks like I've come across the same (or similar) issue. This is on Craft 4.4.2 and Neo 3.7.1.

When a new block is added above an existing block, the fields and content of the new block are replaced by the fields and content of the block beneath it. After the `/actions/neo/input/update-visible-elements` request completes, the block fields are replaced with the fields and content from the block below. I've provided a screen recording to demonstrate. Refreshing the page without saving returns the proper fields to the newly added block. However, if that new block has child blocks, adding a child block results in the same behavior where the fields and content are replaced by the block beneath.

Also, I ran `craft gc/run` as mentioned above and the issue persists.

Any help is appreciated!

https://user-images.githubusercontent.com/29585821/225672192-9f663f6e-839b-4b14-aeef-77f07faf4753.mov

**Comment by ttempleton** [comment] 2023-03-17 07:22
@andrewmenich @sfsmfc @vebjorn If possible, could one of you please send your composer.json/lock and database backup to plugins@spicyweb.com.au along with an example of an entry that is affected.

**Comment by sfsmfc** [comment] 2023-03-17 10:31
Hey @ttempleton thank you for your help. I can send you composer.json/lock, but unfortunately no database at the moment, because we get no ok from our customer. There are many products into the db, which are not official released and therefore I can't get the agree from customer. Would the composer.json/lock enough for you or does it no sense without db?

**Comment by ttempleton** [comment] 2023-03-17 23:02
Thanks for sending the files @andrewmenich, will look into it shortly.

@sfsmfc Yeah, I'll probably need a database, but I definitely understand that not everyone will be allowed to send in their database, and I appreciate the offer.

**Closed** 2023-03-17 23:54 UTC
Labels: bug

**Comment by ttempleton** [comment] 2023-03-18 00:01
It turned out that disabled blocks in the Neo field weren't being accounted for when updating visible field layout elements. That meant, when we tried to match up the `newX` new block ID with the same block's ID as saved for the entry draft, we were getting the wrong block ID. That should be fixed now in Neo 3.7.3.

I'm hoping that's the last of this issue, but please do let me know if this issue still comes up in other cases.

**Comment by sfsmfc** [comment] 2023-03-20 08:41
@ttempleton In our case with Craft 4.3.x and Neo 3.7.3, the issue is resolved and all works as expected. Many thanks for fix.
