### ISSUE TITLE
Neo 	3.5.10: Saving and revision rollback problems

### ISSUE THREAD

**Issue by alexanderloewe** [spicywebau/craft-neo#688] opened 2022-12-07 16:34 UTC
#### Description
On all pagen on witch we use Neo fields we get that error by triing to Roll back to other versions of an entry or by trying to save en entry or other document type like a campain entry.

#### Error message
```
Integrity constraint violation – [yii\db\IntegrityException](https://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html)
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'structureId' in where clause is ambiguous
The SQL being executed was: SELECT `elements`.`id`, `elements`.`canonicalId`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateLastMerged`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`id` AS `siteSettingsId`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `elements`.`dateDeleted`, `neoblocks`.`fieldId`, `neoblocks`.`primaryOwnerId`, `neoblocks`.`typeId`, `neoblocks_owners`.`ownerId`, `neoblocks_owners`.`sortOrder`, `content`.`id` AS `contentId`, `content`.`field_sequenceStyle`, `content`.`field_addressType`, `content`.`field_anchor`, `content`.`field_newsletterSalutation`, `content`.`field_salutation`, `content`.`field_speech`, `content`.`field_answer`, `content`.`field_workplace`, `content`.`field_audioStyle_waxtszpr`, `content`.`field_alignHorizontal`, `content`.`field_alignVertical`, `content`.`field_authors`, `content`.`field_hideAreas`, `content`.`field_description`, `content`.`field_shopDescription`, `content`.`field_newsletterSubject`, `content`.`field_rankStars`, `content`.`field_imageStyle`, `content`.`field_newsletterBoxesStyle`, `content`.`field_code`, `content`.`field_countdownEndDate`, `content`.`field_pageCss`, `content`.`field_fileTitle`, `content`.`field_date`, `content`.`field_endDate`, `content`.`field_startDate`, `content`.`field_dateTime`, `content`.`field_eMail`, `content`.`field_organization`, `content`.`field_newsletterFooterText`, `content`.`field_formStyle_rdfajxca`, `content`.`field_callForm`, `content`.`field_question`, `content`.`field_jobFunction`, `content`.`field_graphDescription`, `content`.`field_graphFbProfile`, `content`.`field_graphFbProfileID`, `content`.`field_graphLiProfile`, `content`.`field_graphSameAs`, `content`.`field_graphTags`, `content`.`field_graphTitle`, `content`.`field_graphTwcard`, `content`.`field_graphTwProfile`, `content`.`field_graphType`, `content`.`field_disclaimerEmailMarketing_rfqnydbh`, `content`.`field_addressNr`, `content`.`field_headerImagesStyle`, `content`.`field_headerHeightStyle`, `content`.`field_headerSliderStyle`, `content`.`field_headerTheme`, `content`.`field_bgColor`, `content`.`field_iconStyle`, `content`.`field_socialMediaIcon`, `content`.`field_paymentMethods_fxdwaway`, `content`.`field_iframe`, `content`.`field_callContent`, `content`.`field_innerCallContent`, `content`.`field_pageJs`, `content`.`field_pageTrackingJs`, `content`.`field_mapLatitude`, `content`.`field_mapPin`, `content`.`field_mapLongitude`, `content`.`field_siteKeywords_aqgjilxv`, `content`.`field_descriptionShort_bjncofst`, `content`.`field_addressCountry`, `content`.`field_readingTime`, `content`.`field_lineType_ldjunwri`, `content`.`field_newsletterLink`, `content`.`field_linkRel_lvovoped`, `content`.`field_linkClass_izaciglg`, `content`.`field_linkQuery`, `content`.`field_linkStyle`, `content`.`field_linkTitle`, `content`.`field_newsletterLinkTitle`, `content`.`field_linkUrl`, `content`.`field_linkTarget`, `content`.`field_newsletterList`, `content`.`field_minimizedContentStyle`, `content`.`field_withRichData_pqmuelti`, `content`.`field_mobileNummer`, `content`.`field_imageMultiStyle`, `content`.`field_lastname`, `content`.`field_names`, `content`.`field_newsletterNav`, `content`.`field_newsletterNavFooter`, `content`.`field_newsletterLanguage`, `content`.`field_note`, `content`.`field_siteNote_fwvejfjp`, `content`.`field_openingHours`, `content`.`field_addressCity`, `content`.`field_password`, `content`.`field_workload`, `content`.`field_addressZip`, `content`.`field_addressZipCity`, `content`.`field_popUpStyle`, `content`.`field_newsletterPreheader`, `content`.`field_price`, `content`.`field_pricingTableStyle_lrjbdaam`, `content`.`field_sourceBuilder_trcybyra`, `content`.`field_fontAlign`, `content`.`field_newsletterFontAlign`, `content`.`field_fontColor`, `content`.`field_pageClass`, `content`.`field_wrapperType`, `content`.`field_seoAltTag`, `content`.`field_seoDesignation`, `content`.`field_seoCanonical`, `content`.`field_seoDescription`, `content`.`field_seoKeywords`, `content`.`field_seoRobots`, `content`.`field_seoSiteName`, `content`.`field_seoRichSchema`, `content`.`field_seoTitle`, `content`.`field_newsletterSmProfiles`, `content`.`field_spacerType`, `content`.`field_languageSetup`, `content`.`field_addressFloor`, `content`.`field_addressStreet`, `content`.`field_addressStreetNr`, `content`.`field_teaserDescription`, `content`.`field_teaserTitle`, `content`.`field_phone`, `content`.`field_multiDate_affazrvv`, `content`.`field_newsletterText`, `content`.`field_text`, `content`.`field_textRtf`, `content`.`field_textStyle`, `content`.`field_textBoxesStyle`, `content`.`field_textblockStyle_kpusnvaf`, `content`.`field_mainTitle`, `content`.`field_newsletterTitle`, `content`.`field_titleStyle`, `content`.`field_titleTag`, `content`.`field_newsletterOverviewType`, `content`.`field_overviewType`, `content`.`field_newsletterOvertitle`, `content`.`field_overTitle`, `content`.`field_subTitle`, `content`.`field_videoEmbed`, `content`.`field_videoEmbedOption`, `content`.`field_videoStyle`, `content`.`field_fullName`, `content`.`field_firstname`, `content`.`field_benefitList`, `content`.`field_website`, `content`.`field_siteWordCount_jluwjtav`, `content`.`field_time`, `content`.`field_quote`, `content`.`field_addressAdditive`, `structureelements`.`root`, `structureelements`.`lft`, `structureelements`.`rgt`, `structureelements`.`level`, `structureelements`.`structureId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `elements` `elements`
INNER JOIN `neoblocks` `neoblocks` ON `neoblocks`.`id` = `elements`.`id`
INNER JOIN `neoblocks_owners` `neoblocks_owners` ON (`neoblocks_owners`.`blockId` = `elements`.`id`) AND (`neoblocks_owners`.`ownerId` = `neoblocks`.`primaryOwnerId`)
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *
FROM `structures` use index(primary)
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
INNER JOIN `neoblockstructures` `neoblockstructures` ON `neoblockstructures`.`structureId` = `structureelements`.`structureId`
WHERE (`neoblocks`.`fieldId`=204) AND (`neoblocks`.`primaryOwnerId`=4017) AND (NOT (`structureId` IS NULL)) AND (`elements_sites`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) AND (`neoblockstructures`.`fieldId`=204) AND (`neoblockstructures`.`siteId`=1)
ORDER BY `structureelements`.`lft`, `neoblocks_owners`.`sortOrder`) `subquery`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `neoblocks` `neoblocks` ON `neoblocks`.`id` = `subquery`.`elementsId`
INNER JOIN `neoblocks_owners` `neoblocks_owners` ON (`neoblocks_owners`.`blockId` = `elements`.`id`) AND (`neoblocks_owners`.`ownerId` = `neoblocks`.`primaryOwnerId`)
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)
ORDER BY `structureelements`.`lft`, `neoblocks_owners`.`sortOrder`
Error Info: Array
(
    [0] => 23000
    [1] => 1052
    [2] => Column 'structureId' in where clause is ambiguous
)
↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'structureId' in where clause is ambiguous
````

#### Other information
- Neo version: 3.5.10
- Craft version: 4.3.4

**Comment by ttempleton** [comment] 2022-12-07 18:24
Closing this issue this as a duplicate of #683.

**Closed by ttempleton** 2022-12-07 18:24 UTC
