### ISSUE TITLE
Error: Attempt to read property "typeId" on bool

### ISSUE THREAD

**Issue by peterurban** [spicywebau/craft-neo#653] opened 2022-09-14 11:35 UTC
#### Description
When trying to save an entry with Neo fields I get the following error:

```
PHP Warning – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Attempt to read property "typeId" on bool
```

Disabling all the Neo blocks makes it possible to save the entry.

#### Steps to reproduce
1. Open entry
2. Press save

#### Other information
- Neo version: 3.3.8
- Craft version: 4.2.4

#### Detailed error message
```
in /var/www/project/cms/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php
```
```
// Create the sibling count for this parent block if this block is the first of its children
if (!isset($blockSiblingCount[$parentId])) {
    $blockSiblingCount[$parentId] = array_fill_keys(
        array_map(
            fn($handle) => $blockTypesByHandle[$handle]->id,
            $atTopLevel ? $topLevelBlockTypeHandles : $childBlockTypes[$parent->typeId]
        ),
        0
    );
}
```

**Comment by ttempleton** [comment] 2022-09-14 14:22
If possible, could you please send a database backup and composer.json/lock files to plugins@spicyweb.com.au, along with instructions regarding an entry where this happens, and we'll have a look.

**Comment by peterurban** [comment] 2022-09-14 19:41
> If possible, could you please send a database backup and composer.json/lock files to [plugins@spicyweb.com.au](mailto:plugins@spicyweb.com.au), along with instructions regarding an entry where this happens, and we'll have a look.

Hi @ttempleton. I have sent you the requested files. Thank you!

**Comment by diegocosta-dev** [comment] 2022-09-15 12:11
I have the same error. This error happens when I try to disable my neo block with matrix block inside. To save I need to disable all matrix blocks inside the neo block.

![759f2084f8edad0b7cf06228e3432c91](https://user-images.githubusercontent.com/48633894/190400249-aad492de-6cc1-43d8-bc22-6d7da168c2b6.png)

**Comment by webrgp** [comment] 2022-09-15 14:27
Same here. Below is a screen shot of the error and the stack trace. I can confirm what @diegocosta-dev said: you have to disable any matrix blocks inside Neo to avoid the error.

<img width="1343" alt="Screen Shot 2022-09-15 at 10 23 38 AM" src="https://user-images.githubusercontent.com/994788/190429403-c9e7f574-9c80-40c1-8f8a-435b44fb01e8.png">

```
yii\base\ErrorException: Attempt to read property "typeId" on bool in /var/www/html/cms/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php:155
Stack trace:
#0 /var/www/html/cms/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/html/c...', 155)
#1 /var/www/html/cms/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php(155): craft\web\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/html/c...', 155)
#2 /var/www/html/cms/vendor/spicyweb/craft-neo/src/Field.php(727): benf\neo\validators\FieldValidator->validateAttribute(Object(craft\elements\Entry), 'contentBlocks')
#3 /var/www/html/cms/vendor/craftcms/cms/src/base/Element.php(2359): benf\neo\Field->validateBlocks(Object(craft\elements\Entry), NULL)
#4 /var/www/html/cms/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldAttribute('field:contentBl...', Array, Object(yii\validators\InlineValidator), Object(benf\neo\elements\db\BlockQuery))
#5 /var/www/html/cms/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:contentBl...')
#6 /var/www/html/cms/vendor/craftcms/cms/src/base/Element.php(2260): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry))
#7 /var/www/html/cms/vendor/yiisoft/yii2/base/Model.php(369): craft\base\Element->afterValidate()
#8 /var/www/html/cms/vendor/craftcms/cms/src/services/Elements.php(2581): yii\base\Model->validate()
#9 /var/www/html/cms/vendor/craftcms/cms/src/services/Elements.php(795): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, NULL)
#10 /var/www/html/cms/vendor/craftcms/cms/src/controllers/ElementsController.php(1262): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#11 [internal function]: craft\controllers\ElementsController->actionApplyDraft()
#12 /var/www/html/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/html/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/html/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('apply-draft', Array)
#15 /var/www/html/cms/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/apply-...', Array)
#16 /var/www/html/cms/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/apply-...', Array)
#17 /var/www/html/cms/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /var/www/html/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/html/cms/web/index.php(12): yii\base\Application->run()
#20 {main}
```

**Comment by ttempleton** [comment] 2022-09-15 15:14
Thanks for sending that through @peterurban - it turned out that in some cases during Neo field validation, when looping through the Neo blocks to validate based on some block type settings, we could lose track of the current block's ancestors, leading `$parent` to be `false` instead of a Neo block.

I'll most likely tag a new release tomorrow, but in the meantime, you can get the fix for this by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.3.8` and running `composer update`.

@diegocosta-dev @webrgp Nested Matrix blocks shouldn't be causing this issue, as the part of the Neo field validation causing the error doesn't check any part of the Neo blocks' contents, just their levels and block type settings. But please do let me know if you still have the error with the next release, and I'll reopen the issue.

**Comment by webrgp** [comment] 2022-09-15 15:27
I've just tried your patch and I am still getting the same error:

```
yii\base\ErrorException: Attempt to read property "typeId" on bool in /var/www/html/cms/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php:155
Stack trace:
#0 /var/www/html/cms/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/html/c...', 155)
#1 /var/www/html/cms/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php(155): craft\web\ErrorHandler->handleError(2, 'Attempt to read...', '/var/www/html/c...', 155)
#2 /var/www/html/cms/vendor/spicyweb/craft-neo/src/Field.php(727): benf\neo\validators\FieldValidator->validateAttribute(Object(craft\elements\Entry), 'contentBlocks')
#3 /var/www/html/cms/vendor/craftcms/cms/src/base/Element.php(2359): benf\neo\Field->validateBlocks(Object(craft\elements\Entry), NULL)
#4 /var/www/html/cms/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldAttribute('field:contentBl...', Array, Object(yii\validators\InlineValidator), Object(benf\neo\elements\db\BlockQuery))
#5 /var/www/html/cms/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:contentBl...')
#6 /var/www/html/cms/vendor/craftcms/cms/src/base/Element.php(2260): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry))
#7 /var/www/html/cms/vendor/yiisoft/yii2/base/Model.php(369): craft\base\Element->afterValidate()
#8 /var/www/html/cms/vendor/craftcms/cms/src/services/Elements.php(2581): yii\base\Model->validate()
#9 /var/www/html/cms/vendor/craftcms/cms/src/services/Elements.php(795): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, NULL)
#10 /var/www/html/cms/vendor/craftcms/cms/src/controllers/ElementsController.php(1262): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#11 [internal function]: craft\controllers\ElementsController->actionApplyDraft()
#12 /var/www/html/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/html/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/html/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('apply-draft', Array)
#15 /var/www/html/cms/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/apply-...', Array)
#16 /var/www/html/cms/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/apply-...', Array)
#17 /var/www/html/cms/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /var/www/html/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/html/cms/web/index.php(12): yii\base\Application->run()
#20 {main}
```

**Comment by ttempleton** [comment] 2022-09-15 15:31
@webrgp Please send your database backup and composer.json/lock files to plugins@spicyweb.com.au, along with instructions regarding an entry where this happens.

**Comment by webrgp** [comment] 2022-09-15 15:37
Sent!

**Comment by webrgp** [comment] 2022-09-15 16:58
Under Entries > Pages > Our Company. The first content block "Featured": disabled and hit save.

**Closed** 2022-09-16 01:13 UTC
Labels: bug

**Comment by ttempleton** [comment] 2022-09-16 02:43
Thanks for sending that through @webrgp. I've tweaked the field validator's handling of disabled blocks which fixes that error. Neo 3.3.9 has just been released with that fix.

**Comment by diegocosta-dev** [comment] 2022-09-16 12:13
@ttempleton Thanks for fixing this

**Comment by ccchapman** [comment] 2023-01-16 05:10
We seem to be experiencing this issue on Neo 3.4.0 and Craft CMS 4.3.1.  The entry Neo field has many blocks including enabled and disabled.

```
yii\base\ErrorException: Attempt to read property "typeId" on bool in /home/site/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php:163
Stack trace:
#0 /home/site/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError()
#1 /home/site/vendor/spicyweb/craft-neo/src/validators/FieldValidator.php(163): craft\web\ErrorHandler->handleError()
#2 /home/site/vendor/spicyweb/craft-neo/src/Field.php(727): benf\neo\validators\FieldValidator->validateAttribute()
#3 /home/site/vendor/craftcms/cms/src/base/Element.php(2402): benf\neo\Field->validateBlocks()
#4 /home/site/vendor/yiisoft/yii2/validators/InlineValidator.php(77): craft\base\Element->validateCustomFieldAttribute()
#5 /home/site/vendor/yiisoft/yii2/validators/Validator.php(260): yii\validators\InlineValidator->validateAttribute()
```

**Comment by ttempleton** [comment] 2023-01-17 12:12
@ccchapman could you please upgrade to the latest Neo release (3.5.16) and let me know if that's still happening?

**Comment by ttempleton** [comment] 2023-01-18 08:59
Pretty concerning that it was still happening before you deleted the disabled blocks. If you have a database backup with the disabled blocks and you're able to send it to us, could you please send it and your composer.json/lock files to plugins@spicyweb.com.au and we'll have a look.

**Comment by ttempleton** [comment] 2023-02-08 01:25
Thanks for sending that in @ccchapman. It turned out that was happening due to old provisional draft data where a block existed at a different level to its level on the live entry, and Neo's getting the incorrect level data for that block. The cause for that is the same as for issue #682. In your case, since the provisional draft was out of date, I was able to confirm that discarding the provisional draft (which was created by user ID 63440) allows saving the affected entry.
