### ISSUE TITLE
Handling "Lock wait timeout exceeded" errors when saving entries with numerous Neo modules

### ISSUE THREAD

**Issue by aaronbushnell** [spicywebau/craft-neo#257] opened 2019-09-17 21:09 UTC
#### Description
I have a couple Craft entries that use Neo pretty extensively and—upon save—throw the following error:

```
yii\db\Exception: Uncaught exception 'yii\db\Exception' with message 'SQLSTATE[HY000]:
General error: 1205 Lock wait timeout exceeded; try restarting transaction
The SQL being executed was: UPDATE `craft_elements` SET `fieldLayoutId`=3307, `enabled`=1, `archived`=0, `dateUpdated`='2019-09-17 19:47:00' WHERE `id`=35637' in vendor/yiisoft/yii2/db/Schema.php:664
```

Currently our `innodb_lock_wait_timeout` is set to `50` and that _seems_ like it'd be enough time to process any entry with Neo fields, even ones using it pretty extensively. 

Is this a common problem? Anything that might help us optimize things a bit? Or do we need to raise our `innodb_lock_wait_timeout` value to something higher than `50`?

#### Other information
- Neo version: 2.3.7
- Craft version: Craft Pro 3.2.10
- PHP version: 7.0.33
- MySQL version: MySQL 5.6.35
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: N/A
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: N/A
- Is eager-loading used? N/A

**Comment by pvldigital** [comment] 2019-09-20 00:51
Hi @aaronbushnell, `50` should be enough when saving an entry with neo. 

Can you estimate how many blocks are within the entry that's being saved? A huge amount of blocks being saved would extend the time needed which is most likely the issue.

For now, increasing the time to `120` or higher should be enough time to allow the entry to be saved.

**Comment by aaronbushnell** [comment] 2019-09-20 00:56
Thanks for the recommendation! Let me try that and I’ll get back to you on what happens with that adjustment.

**Comment by pvldigital** [comment] 2019-09-23 05:14
Hi @aaronbushnell, I'm closing this issue for now. If it continues happening i'll have a further look into the issue.

**Comment by OscarBarrett** [comment] 2020-02-27 04:47
We were running into this issue with a complex section. The solution was to disable versioning which almost halved the number of queries being made on save (4800 vs 2600) and eliminated any lock issues.

**Comment by aaronbushnell** [comment] 2020-02-27 16:11
Thanks, @OscarBarrett! How were you able to get the number of queries on a save event?

**Comment by OscarBarrett** [comment] 2020-02-28 01:51
You can find it on the Yii debug toolbar - after saving an entry, select the POST request that was made and open up the Database tab.

**Comment by aaronbushnell** [comment] 2020-03-05 02:10
Wow I had _no_ idea about this! Thanks, @OscarBarrett!

**Comment by lenvanessen** [comment] 2020-03-10 16:28
Same issue here, is there a possibility that this gets reopened and NEO takes a look at how to improve this? We'd like to keep versioning, but then saving takes around 60 seconds or so.

**Comment by aaronbushnell** [comment] 2020-03-10 18:47
Do delta updates from Craft 3.4 help at all here? Which should allow only the changes Neo content to have to get processed?

**Comment by lenvanessen** [comment] 2020-03-10 19:57
We're on Craft 3.4.9, with 2 sites

**Comment by aaronbushnell** [comment] 2020-03-10 20:23
Ah so it sounds like there’s still some Neo optimizations to be made here.

**Comment by pvldigital** [comment] 2020-03-10 21:18
@lenvanessen sure I'll reopen and will have a look at this issue again.

@aaronbushnell the delta updates should mitigate the issue but it looks like it might not be behaving correctly. I'll revisit this first which should improve the situation.

**Comment by aaronbushnell** [comment] 2020-03-10 22:43
No problem, @pvldigital! If it's useful I could send you a DB, our codebase and some reproduction steps that trigger these types of issues?

**Comment by pvldigital** [comment] 2020-03-10 22:52
Hi @aaronbushnell,

That would be helpful, the db and reproduction steps would be great. You can send them through to plugins@spicyweb.com.au and I'll have a look.

**Comment by lenvanessen** [comment] 2020-03-11 16:22
@pvldigital if you want, we can provide test-data as well. Our set-up does 7700 queries when changing a single field, consuming 70mb of memory and eventually failing. And this is on a high-performance Heroku database.

![Schermafbeelding 2020-03-11 om 17 19 55](https://user-images.githubusercontent.com/23024452/76439504-c6e32d80-63bc-11ea-9059-bbcfed8410f8.png)

We have around 16 blocks on this page. When adding more sites to the cms, it basically becomes unusable. We have a set-up where we need 11 sites, but it renders impossible to fill the content at the moment

**Comment by aaronbushnell** [comment] 2020-03-11 16:25
It might take me a bit to prepare our data so if @lenvanessen‘s helps expedite things here that might help troubleshoot this further!

**Comment by pvldigital** [comment] 2020-03-12 05:14
@aaronbushnell @lenvanessen i've just released a new version which has a change for delta updates. hopefully it should help mitigate the issue.

I'll still wait for the databases for a more in-depth look at the issue.

**Comment by lenvanessen** [comment] 2020-03-12 08:25
@pvldigital as a heads-up, it lowers it to 4000 queries when changing 1 field. Other actions like duplication of an entry and storing an new one with all new content are still pretty much impossible unfortunately.

**Comment by lenvanessen** [comment] 2020-03-12 15:58
@pvldigita Maybe it helps, but I'm seeing a lot of duplicate queries, most of the queries come by 4 times.

**Comment by pvldigital** [comment] 2020-03-13 01:38
@lenvanessen @aaronbushnell 

small update: I found out that the creation of the neo structures is causing the large amounts of queries. I'm going to have to redo how the structure is retrieved and recorded to prevent this issue.

I'll keep you all updated on my progress.

**Comment by pvldigital** [comment] 2020-03-13 07:51
@lenvanessen @aaronbushnell changes has been made in the `craft-3-dev` branch. Will be testing it thoroughly before releasing. From my preliminary testing the performance is much better now.

**Comment by lenvanessen** [comment] 2020-03-13 09:07
@pvldigital I'll test as well, let you know if I find anything.

**Comment by pvldigital** [comment] 2020-03-13 09:18
@lenvanessen reminder to test it locally.

The migration is kinda iffy at the moment so if you could report back after testing that would be good.

use to migrate"
`./craft migrate/up --plugin=neo`

**Comment by lenvanessen** [comment] 2020-03-13 09:41
Locally migration went fine, on acceptance got the following error:
```
    > add column sortOrder integer NOT NULL to table {{%neoblocks}} ...Exception: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "sortOrder" contains null values
The SQL being executed was: ALTER TABLE "neoblocks" ADD "sortOrder" integer NOT NULL (/app/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE "ne...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('ALTER TABLE "ne...')
#2 /app/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /app/vendor/spicyweb/craft-neo/src/migrations/m200313_015120_structure_update.php(32): yii\db\Migration->addColumn('{{%neoblocks}}', 'sortOrder', Object(yii\db\ColumnSchemaBuilder))
#4 /app/vendor/craftcms/cms/src/db/Migration.php(52): benf\neo\migrations\m200313_015120_structure_update->safeUp()
#5 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): craft\db\Migration->up()
#6 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(200): yii\console\controllers\BaseMigrateController->migrateUp('m200313_015120_...')
#7 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(314): yii\console\controllers\BaseMigrateController->actionUp(0)
#8 [internal function]: craft\console\controllers\MigrateController->actionUp(0)
#9 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /app/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('up', Array)
#12 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#13 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#14 /app/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/up', Array)
#15 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/up', Array)
#16 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /app/craft(22): yii\base\Application->run()
#18 {main}
```

**Comment by pvldigital** [comment] 2020-03-13 11:57
ah i should've allowed nulls. made a change for it.

**Comment by lenvanessen** [comment] 2020-03-13 16:15
@pvldigital well the migrations work now, but:

```
SQLSTATE[42803]: Grouping error: 7 ERROR: column "neoblocks.sortOrder" must appear in the GROUP BY clause or be used in an aggregate function
LINE 12: ORDER BY "neoblocks"."sortOrder"
^
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId"
FROM "elements" "elements"
INNER JOIN "neoblocks" "neoblocks" ON "neoblocks"."id" = "elements"."id"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
INNER JOIN "content" "content" ON ("content"."elementId" = "elements"."id") AND ("content"."siteId" = "elements_sites"."siteId")
WHERE ("neoblocks"."fieldId"=7) AND ("neoblocks"."ownerId"=976) AND ("elements_sites"."siteId"=6) AND ("elements"."archived"=FALSE) AND ("elements"."enabled"=TRUE) AND ("elements"."dateDeleted" IS NULL) AND ("elements_sites"."enabled"=TRUE) AND ("elements"."draftId" IS NULL) AND ("elements"."revisionId" IS NULL)) "subquery"
INNER JOIN "neoblocks" "neoblocks" ON "neoblocks"."id" = "subquery"."elementsId"
INNER JOIN "elements" "elements" ON "elements"."id" = "subquery"."elementsId"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId"
INNER JOIN "content" "content" ON "content"."id" = "subquery"."contentId"
ORDER BY "neoblocks"."sortOrder"
Error Info: Array
 ```

**Comment by lenvanessen** [comment] 2020-03-15 08:48
@pvldigital we've tested it further on mysql. Back-end performance is much better, howerev the `level` query doesn't return any results anymore.

`entry.pageparts.level(0).all()` is empty, even though there are blocks at this level!

**Comment by pvldigital** [comment] 2020-03-15 22:34
Hi @lenvanessen,

Hmm I'll look into the level query issue.

As for the migration, that's error appears when using postgre right?

**Comment by pvldigital** [comment] 2020-03-16 00:51
@lenvanessen level querying should be fixed with the latest commit in the dev branch.

**Comment by lenvanessen** [comment] 2020-03-16 07:24
Yes, that error appears using postgres, but not in the migratiion, when trying to save an entry.
Also, I think since the new version, we're not able to apply config changes anymore:

```
Applying changes from project.yaml ... error: Changes to the project config are not possible while in read-only mode.
       Script ./craft project-config/sync handling the post-install-cmd event returned with error code 
```

**Comment by pvldigital** [comment] 2020-03-17 00:23
@lenvanessen added a small change for postgres. i've also re-added the project config read only check which should prevent that issue.

**Comment by lenvanessen** [comment] 2020-03-17 07:59
@pvldigital cool, when do you expect a stable version to drop?

**Comment by pvldigital** [comment] 2020-03-17 09:44
@lenvanessen within this week for sure. I’ll just need to test it thoroughly first and fix any issues I can find.

**Comment by lenvanessen** [comment] 2020-03-18 08:15
@pvldigital well we've increased the number of sites to a 100 and it's still working.

By the way, nested level queries are not working.
`{% set columns = block.children.level(0) %}`

**Comment by pvldigital** [comment] 2020-03-19 02:30
@lenvanessen I've made some changes in the latest commit which should solve most querying issues. Can you test to see if it's still performing well? From what I can see there's a slight increase.

**Comment by lenvanessen** [comment] 2020-03-19 07:46
@pvldigital looks good, can't find any bugs on my end.

**Comment by pvldigital** [comment] 2020-03-19 21:40
@lenvanessen cool. I'm going to do a final round of testing and will make a release some time today.

**Comment by pvldigital** [comment] 2020-03-22 21:13
@aaronbushnell @lenvanessen new release has been made for this issue.

**Closed** 2020-03-22 22:25 UTC

**Comment by markjoeljimenez** [comment] 2020-03-30 22:12
#324

**Comment by i-internet** [comment] 2024-02-02 19:51
Can anyone tell how exactly this issue got resolved ? 

'''

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
The SQL being executed was: UPDATE `tbl_batch` SET `batch_cohort_id`=1275 WHERE `id`=7222#0 /vendor/yiisoft/yii2/db/Command.php(1325): yii\\db\\Schema->convertException(Object(PDOException), \'UPDATE `tbl_bat...\')
#1 /vendor/yiisoft/yii2/db/Command.php(1120): yii\\db\\Command->internalExecute(\'UPDATE `tbl_bat...\')
#2 /vendor/yiisoft/yii2/db/ActiveRecord.php(336): yii\\db\\Command->execute()

'''
