### ISSUE TITLE
Copy/pasted blocks with children lose their child blocks after revision updates

### ISSUE THREAD

**Issue by chrispinion** [spicywebau/craft-neo#786] opened 2023-09-21 19:07 UTC
### Bug Description

Hi @ttempleton, I'm hitting an issue when copying/pasting blocks that contain children. After Craft updates the revision, the children inside the pasted block will disappear suddenly. I've tested pasting single blocks without children, and those seem to work as intended. Here's a screen recording of the issue happening:

https://github.com/spicywebau/craft-neo/assets/29065774/bd4d73f8-d9cc-4c65-8975-7d51ffcfa0d4

I'll include the specific entry where this is happening in my email, with my composer.json/lock and database file.

### Steps to reproduce

1. Copy a block containing a child
2. Paste the block
3. Wait for revision to finish updating, then the block's children disappear

### Expected behaviour

Pasted blocks should remain after revision updates

### Neo version

3.9.0

### Craft CMS version

4.5.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2023-09-22 03:00
This looks to specifically affect the child block UI element, so I'll close it as a duplicate of #777. Try the command in https://github.com/spicywebau/craft-neo/issues/777#issuecomment-1730729604 and see if that fixes it; please let me know how you go in that issue.

**Comment by ttempleton** [comment] 2023-09-22 09:57
Actually, digging into it a bit further, I think this one is unrelated.

**Closed** 2023-09-22 10:18 UTC
Labels: bug

**Comment by ttempleton** [comment] 2023-09-22 10:22
That should be fixed now in 3.9.1.
