### ISSUE TITLE
Preview mode showing lage vertical space between some fields

### ISSUE THREAD

**Issue by icreatestuff** [spicywebau/craft-neo#716] opened 2023-02-21 12:22 UTC
### Bug Description

Within a Neo field I have a block with a couple of fields 'Vertical Padding Top' and 'Vertical Padding Bottom' in this example that are set to 2 columns each so they float next to each other on large enough screens/windows. This works fine. When viewing the entry in preview mode however, these fields are stacked on top of each other and show a very large gap between them.

![Screenshot 2023-02-21 at 11 54 22](https://user-images.githubusercontent.com/1300714/220339400-e055d110-8120-4fea-afd3-46a2b1c4ddd9.png)

As far as I can tell this only becomes a problem if there is a **collapsed** block before the block with the problematic field spacing. If the block before is expanded, the huge space isn't visible.

![Screenshot 2023-02-21 at 11 54 22](https://user-images.githubusercontent.com/1300714/220343746-8ec2954a-a2a7-43f3-8329-0f7dc9989590.png)

I inspected the source code and all I was able to see adjust that had any impact was an `::after` pseudo-element on the field input, selector `.field > .input:after`. Toggling the `display` or `clear` CSS properties caused the gap to disappear as shown in the following screenshot.

![Screenshot 2023-02-21 at 11 54 32](https://user-images.githubusercontent.com/1300714/220339673-9d54814c-9f8c-4800-bf99-682190a198eb.png)

I wasn't sure if this was a bug with Neo or with Craft but as it seemed to only be a problem in Neo fields so I've posted here first.

### Steps to reproduce

1. Create a Neo field with a block
2. Add some fields to the block and adjust the column layout for the fields so multiple fields float next to each other
3. Create an entry with at least 2 blocks in the Neo field.
4. Collapse the first block
5. View the entry in Preview mode
6. Look at the contents of the 2nd block

### Expected behaviour

When in preview mode the vertical field spacing should be consistent regardless of if any sibling blocks are collapsed or expanded.

### Neo version

2.13.16

### Craft CMS version

Pro 3.7.67

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2023-02-23 09:49
I'm not seeing this happen so far - is there any chance you can share a screenshot with the expanded first block? Wondering if there's something in that block that could somehow be pushing the next block's content down.

**Comment by icreatestuff** [comment] 2023-02-23 15:51
Interesting, I've noticed now that it actually appears to be a problem if the block beforehand has a child block. If either the child block **or** the parent block is collapsed, the next block is showing the spacing issue. Here's a screengrab showing the parent block and child expanded in non-preview mode.

![Screenshot 2023-02-23 at 15 48 55](https://user-images.githubusercontent.com/1300714/220958992-4b6513e8-67af-4015-a86e-8948577dc18c.png)

You'll notice too that the 'Column' child block has the option for a further child block of 'Call To Action'. I'm not sure if that's relevant, but even without adding a CTA block the problem occurs.

Many thanks

**Comment by ttempleton** [comment] 2023-02-26 01:18
Unfortunately I'm still unable to reproduce this. If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au, along with which entry is being affected and which browser you're using, and we'll have a look.

**Comment by ttempleton** [comment] 2023-04-05 09:08
Closing this issue as not reproducible, but if the issue persists, please let us know and we'll reopen.

**Closed by ttempleton** 2023-04-05 09:08 UTC
Labels: bug, not reproducible
