### ISSUE TITLE
Blocks are visible when viewing recent revisions but not for all revisions.

### ISSUE THREAD

**Issue by mike-moreau** [spicywebau/craft-neo#805] opened 2023-10-12 20:57 UTC
### Bug Description

We have Craft configured with a max of `50` revisions via general config: `'maxRevisions' => 50`

The revisions are viewable in the CMS as expected. Some are a few minutes old, others are several months old.

The recent revisions (in this case, made the same day) are working as expected. I can view them and restore their content.

The older revisions show a blank blocks field. I can still restore the content; but, if I do the block structure is lost. All blocks are output as level 1 without any nesting.

<img width="1082" alt="Screenshot 2023-10-12 at 3 45 42 PM" src="https://github.com/spicywebau/craft-neo/assets/92817780/2f62890b-a24b-46b8-b28a-8989aecab364">

### Steps to reproduce

1. Set up a section with a Neo field
2. Create a few revisions
3. Wait a while (hopefully not a few months, ha ha)
4. See if the Neo blocks can be viewed and restored

### Expected behaviour

Entry revision and blocks field to restore with structure when reviewing revisions.

### Neo version

3.9.5

### Craft CMS version

4.5.6.1

### What is the affected Neo field's propagation method?

 Only save blocks to the site they were created in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by mike-moreau** [comment] 2023-10-12 20:57
If there's any further info I can provide to be of assistance please let me know, thanks!

**Comment by ttempleton** [comment] 2023-10-16 09:50
Is there any chance you're disabling Craft's `runQueueAutomatically` setting in your general config? There was a Neo bug a little while ago where revision block structure creation was only happening with queue jobs, so potentially if any jobs were cleared from the queue for whatever reason, the block structures would never be created. Now we check that setting and make sure we create the revision block structures immediately if the setting is disabled.

If you're not disabling that setting, then it's possible that it was a bug that also got fixed by a bugfix for something else in the last few releases. I'll recommend to keep checking it and make sure that the blocks aren't still disappearing from any revisions where you've seen them recently, and let me know if that does happen. I'll keep this issue open for a while in case it happens.

**Comment by mike-moreau** [comment] 2023-10-16 13:41
@ttempleton yes, we have disabled the setting in production. In this case, Craft's queue is running as a Daemon on a Laravel Forge provisioned server. So sounds like the first option could be likely?

**Comment by mike-moreau** [comment] 2023-10-16 19:41
@ttempleton is there any way to re-create the block structures for revisions?

**Comment by mike-moreau** [comment] 2023-10-16 20:42
@ttempleton if I may trouble you for one more question, do you know which version of Neo the bug was introduced in, and which version it was fixed in?

**Comment by ttempleton** [comment] 2023-10-17 11:34
I haven't gone back and tested, but the use of queue jobs to save block structures in certain cases was introduced in 2.7.0, so potentially as early as then. It was fixed in 3.7.9.

Unfortunately, since the block structure data is passed to the job to then create the block structure, if the job is cleared before it's executed, the block structure data is lost and can't be recreated. If you were to restore the revision, you'd need to manually move the blocks back into place. Sorry for the inconvenience caused due to that bug.

I'll assume that's the cause of it and close the issue. Please do let me know if it happens again with newer revisions, though, and I'll reopen it.

**Closed by ttempleton** 2023-10-17 11:34 UTC
Labels: bug
