### ISSUE TITLE
Changing Entry Type deletes all Blocks

### ISSUE THREAD

**Issue by wedot** [spicywebau/craft-neo#453] opened 2021-05-19 00:08 UTC
#### Description
By changing the Entry Type Neo deletes all Neo Blocks. 
I made a video with the issue: https://www.loom.com/share/575065569f764d83a28b271f80f9c8b6

#### Other information
- Neo version: 2.9.8
- Craft version: 3.6.15

**Comment by ttempleton** [comment] 2021-05-21 10:51
This is a duplicate of #298; the Neo field hasn't finished loading by the time you save the entry after changing the entry type, which is what causes the blocks to disappear.

**Closed by ttempleton** 2021-05-21 10:51 UTC
