### ISSUE TITLE
Javascript Error When Trying to Add a Block in Neo

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#879] opened 2024-04-11 16:09 UTC
### Bug Description

When I try to add a block to a Neo field in the control panel I get a spinner and an error in the javascript console. The response that comes into axios is:
"name": "PHP Warning",
"message": "Undefined array key 0",
"code": 2

If you cannot re-create, I can send a backup and composer files.

### Steps to reproduce

1. Try to add a new block
2.
3.

### Neo version

4.1.2

### Craft CMS version

4.8.9

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2024-04-11 23:50
Could you please send the DB backup and composer files to plugins@spicyweb.com.au along with information about an entry where this is happening, and we'll have a look.

**Comment by ttempleton** [comment] 2024-04-13 11:18
Thanks for sending the files. This error turned out to be caused by the Colour Swatches plugin, and was fixed in version [4.5.1](https://github.com/craftpulse/craft-colour-swatches/releases/tag/4.5.1) of that plugin.

**Closed by ttempleton** 2024-04-13 11:18 UTC
Labels: bug, bug status: unconfirmed
