### ISSUE TITLE
All blocks lost when converting to Matrix field

### ISSUE THREAD

**Issue by j-greig** [spicywebau/craft-neo#126] opened 2018-03-12 13:59 UTC
When I change the Neo field to a Matrix, everything inside it disappears. Am I doing something wrong?

There are a fair number of blocks defined...

![image](https://user-images.githubusercontent.com/616194/37287808-95d557ee-25fd-11e8-9917-2b9422345ce6.png)

**Comment by kisonay** [comment] 2018-03-14 15:31
I believe this is expected. If you change the field type of a field, data will be lost. If you wanted to convert a neo field to a matrix, it would need to be manual (recreate the field with the matrix type.)

**Comment by j-greig** [comment] 2018-03-15 09:18
Not according to https://github.com/benjamminf/craft-neo/issues/17 and the relates notes that follow... ?

**Comment by kisonay** [comment] 2018-03-15 12:11
You talk about changing the field from a Neo to matrix field, #17 says that is converts them when Neo is uninstalled. Which are you trying to do?

**Comment by ttempleton** [comment] 2019-01-05 12:37
@j-greig Sorry that this issue was not resolved sooner, hopefully this has since been sorted out, but if not:

When changing a Neo field to Matrix, after selecting Matrix on the field type dropdown, you should have a button appear below the dropdown that will perform the conversion process.  If you're still experiencing this issue, can you please confirm the version of Neo you're using, and whether or not you're seeing that button (and if not, can you please let me know if you're experiencing any JavaScript errors) or whether the issue is that you're using that button but the process is not completing?

**Comment by ttempleton** [comment] 2019-03-24 11:15
We'll close this issue now, given its age and no other reports of the issue, and that we've been unable to find a case where a Neo-to-Matrix field conversion loses all of its block types or the convert button doesn't appear.  If you do continue to experience the issue, though, let us know and we'll reopen.

**Closed by ttempleton** 2019-03-24 11:15 UTC
Labels: not reproducible
