### ISSUE TITLE
Nested Neo Blocks are empty when using a GraphQL Query

### ISSUE THREAD

**Issue by lucasvallenet** [spicywebau/craft-neo#518] opened 2021-11-16 20:08 UTC
#### Description
I'm using nested multiple block in Neo with 2 levels.
When adding the GraphQL query, my children of the Neo blocks return an empty array

#### Steps to reproduce
1. Setup a nested neo block
2. Query the block
3. No data returned

**Query**
```
neo {
    ...on neo_blockParent_BlockType {
          typeHandle
          children {
              id
              ...on neo_blockParent_BlockType {
                  typeHandle
              }
         }
    }
}
```

**Result**
```
"builder": [
    {
          "blockParent",
          "children": []
    }
]
```

**Note**
If it is used with the `neo(level:0)` parameters it returns the data

#### Other information
- Neo version: 2.11.17
- Craft version: 3.6.4

**Comment by we-do** [comment] 2021-11-16 20:36
I just had this too. They've already fixed it and I can confirm it works, but you have to manually replace the code ([Block.php](https://github.com/spicywebau/craft-neo/tree/master/src/gql/resolvers/elements)) for now. 

https://github.com/spicywebau/craft-neo/commit/969119e9a541039a0114f916a8bb7aecfb1b299f

**Comment by ttempleton** [comment] 2021-11-16 21:37
Closing this issue as a duplicate of #516.

**Closed by ttempleton** 2021-11-16 21:37 UTC
