### ISSUE TITLE
Content from draft is not shown when setting block query parameters

### ISSUE THREAD

**Issue by pablofernandezgh** [spicywebau/craft-neo#181] opened 2019-01-28 10:56 UTC
When I loop over the content of an EntryDraft, I get the content from the published Entry, not from the EntryDraft

When I do

```
foreach ($entryDraft->neoBlocks->level(1)->all() as $neoBlock) {

    $neoBlock->owner->draftId

}
```

I get null, so I assume the block doesn't understand it belongs to an EntryDraft and not to an Entry

Neo version: **2.2.1**
Craft version: **3.1.5**
Is the affected Craft installation multi-site: **Yes**
(if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: **No**

**Comment by ttempleton** [comment] 2019-01-28 11:36
Can you please provide the following:
- Neo version:
- Craft version:
- Is the affected Craft installation multi-site:
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:

**Comment by pablofernandezgh** [comment] 2019-01-28 12:45
@ttempleton I've updated my issue with the info you requested

**Comment by ttempleton** [comment] 2019-01-29 01:12
Thanks @pablofernandezgh!  Confirming that I can see the behaviour from Neo that you describe, and that, for example, a Matrix field works in the way that you would expect.  We will investigate and hopefully it won't be too long before we can implement a fix.

**Comment by ttempleton** [comment] 2019-02-08 02:34
Hi @pablofernandezgh,

Can I ask which method you're using to get the entry draft?

Craft's entry revisions service has the [`getDraftsByEntryId()`](https://docs.craftcms.com/api/v3/craft-services-entryrevisions.html#method-getdraftsbyentryid) and [`getDraftById()`](https://docs.craftcms.com/api/v3/craft-services-entryrevisions.html#method-getdraftbyid) methods and, while the latter will include the draft content, the former will not unless its `$withContent` parameter is `true`.  I've tested and confirmed that Neo field content for a draft is included for `getDraftById()`, and for `getDraftsByEntryId()` if `$withContent` is true; otherwise, it will query for the associated published entry's blocks.  My testing has also confirmed that this is consistent with how Matrix fields work with entry drafts.

I'm going to remove the 'bug' label from this issue for now, since this is the expected behaviour if using `getDraftsByEntryId()` with `$withContent` set to `false` (as it is by default).  If you are using a method where you'd expect the draft content to be included, or you're using another method to get the draft, please let us know and we'll proceed from there.

**Comment by pablofernandezgh** [comment] 2019-02-11 11:08
Hello @ttempleton 
I get the entry draft with `getDraftById()`

Here's my code :
```
$entryDraft = (new \craft\services\EntryRevisions())->getDraftById((int)$draftId);
foreach ($entryDraft->neoBlocks->level(1)->all() as $neoBlock) {
    var_dump($neoBlock->richText);
    var_dump($neoBlock->owner->draftId);
}
```

The richText outputted is the one from the published entry, not from the draft
The draftId is always null

**Comment by ttempleton** [comment] 2019-02-15 11:06
Thanks @pablofernandezgh.  It looks like setting the `level` (or other block query parameters) causes it to query the database instead of using the draft content.  It also looks like Matrix fields do the same (tested with querying for a specific `typeId`), which I think is probably the intended behaviour, [since Matrix fields work the same way with live preview](https://craftcms.stackexchange.com/a/8880).

That said, we could probably use much of Neo's live preview code to allow this to some extent, so we'll look at adding this in the near future.

**Comment by ttempleton** [comment] 2019-02-19 01:35
This will be included in the next Neo release, within the next day or two.

**Closed by ttempleton** 2019-02-19 01:35 UTC
Labels: improvement
