### ISSUE TITLE
Multi level reorder

### ISSUE THREAD

**Issue by BryceBubbles** [spicywebau/craft-neo#27] opened 2016-06-08 04:13 UTC
It would be super helpful if blocks could be dragged in and out of different levels.
At the moment, if you have a block as a child of say a column block, then you have to recreate it if you now need it to be in another column.

**Comment by benjamminf** [comment] 2016-06-09 00:15
Hey Bryce, yeah this is a feature that many have requested. Unfortunately it's quite a technical challenge, and the Garnish dragging API has no support for this particular functionality.

I've really wanted this functionality as well, so the feature is not off the table. But if I'm unable to implement moving children in and out via dragging, then it might have to be something like an option to move a block to another in the block's dropdown menu.

**Comment by benjamminf** [comment] 2016-06-25 08:01
Decided to take the plunge and try and implement multi-level drag sorting. I'm having to break apart the Garnish dragging API and build a custom one, but it's looking promising. I'm a little hesitant to say for sure it'll be implemented, but I think it can be expected in a `1.4.x` release.

**Comment by benjamminf** [comment] 2016-06-26 07:41
Well, it's done. Didn't expect it'd be as simple as it was. Multilevel dragging has been implemented, just need to add in restrictions so you can't drag a block into a place it doesn't belong. This should be completed over the next week. Exciting times.

**Comment by BryceBubbles** [comment] 2016-06-26 20:42
Awesome, looking forward to it :)

**Comment by theskyfloor** [comment] 2016-06-29 17:32
This sounds amazing! Great work as always.

**Comment by benjamminf** [comment] 2016-07-21 00:38
Thought I'd give an update since it's been a bit more than a few weeks. I ran into issues when adding restrictions and had to rethink my approach. I now have a solution that works but I haven't had time to finish it lately. No ETA yet unfortunately but it'll come eventually!

**Comment by theskyfloor** [comment] 2016-07-21 01:20
Sweet - excited either way - another killer feature.

**Comment by kepano** [comment] 2016-07-22 15:38
Very excited about this feature! Just created an awesome flexbox grid system using Neo and it would be very helpful to move columns from one container to another.

**Comment by joshangell** [comment] 2016-08-03 14:36
Hey @benjamminf just wondering if you have a timeline on this? We’re re-developing how we do our grids and like many want to use a flexbox approach, this leads us to have nested sets of columns and blocks and therefore we want to drag a block from one column to another.

Awesome plugin though man, such a great contribution to the community - massive thanks 😄

**Comment by benjamminf** [comment] 2016-08-03 23:45
Hey Josh, no timeline yet unfortunately. I've become pretty busy these last couple of weeks so I haven't had much time to spend on Neo. Block restrictions have really thrown a spanner in the works, as there's so many edge cases to consider. I'm considering a pre-release of 1.4.0 though, which will support multi-level dragging but without the block restrictions. Just wondering if anyone would find that useful though?

**Comment by theskyfloor** [comment] 2016-08-04 15:22
I would love to test it even as it currently stands... At least how I usually set up my neo fields I would suspect that my clients would be dragging things into the correct locations anyway but would love to test and see if that is true or not.

**Comment by joshangell** [comment] 2016-08-04 18:20
Agreed - I would love to actually see it in action! I haven't tried it but can we just play with the relevant branch?

-Josh
angell.io - custom development and consultancy for Craft CMS

**Comment by benjamminf** [comment] 2016-08-05 01:20
`feature/multilevel-drag-sort` is the relevant branch, but none of the new code is compiled in any branch other than `master`. Also, the algorithm I had working I've removed in the later commits. That said I can rollback to a working state and supply the compiled files here in this issue thread. I'll do it over the weekend.

**Comment by benjamminf** [comment] 2016-08-23 11:58
Forgot about this - better late than never I suppose.

Okay so [here's the appropriate files](https://github.com/benjamminf/craft-neo/files/432334/resources.zip). Just replace `main.js and `main.map.js` under the `resources/` directory. Keep in mind this is the old version of the multilevel drag sort, and there are some weird bugs. But it should be pretty usable so give it a go if you're interested.

Again, no update, but I've finally had some time to work on this plugin this week. Outside of work I've been preoccupied with study so that's eating up a lot of my time. However I anticipate I'll have some more time free to work on this going forward.

**Comment by theskyfloor** [comment] 2016-08-23 12:57
Thanks! I just tested it and for my typical page builder set up, it actually works really well... I don't know if you have any restrictions in place in the JS you sent but I can't seem to drag blocks where they don't belong but I can drag them between levels where they are safe and appropriate. Hope the feature can be refined and rolled out

**Comment by benjamminf** [comment] 2016-08-23 23:56
Great to hear @theskyfloor 👍  Yeah there are restrictions in place but it's not perfect (it's where most of the bugs are). It should work fine for simple situations, it's mostly when you have >2 level deep blocks that it starts getting hairy.

**Comment by aenrii** [comment] 2016-09-15 21:48
Does replacing the same files work in the latest release (1.3.5)?

**Comment by benjamminf** [comment] 2016-09-15 22:28
@aenrii I don't think so. I wouldn't try it at least. I can build these files again if you want to try it on 1.3.5?

**Comment by aenrii** [comment] 2016-09-20 03:37
@benjamminf no worries, I can hold on for the proper release. 👍  Cheers!

**Comment by 23d1** [comment] 2016-10-30 21:06
Oh no! 1.4.1? ;)

**Comment by benjamminf** [comment] 2016-10-30 21:43
:( I know. It's a beast of a feature and while I had it planned for 1.4.0 I didn't want to hold off another month before releasing. Now that all of the other major features I had planned are out of the way, multi level reordering is receiving all of my focus 👍 So, 1.5.0 for absolute certain. And I doubt there'll be many, if any, patch releases on 1.4.0.

**Comment by dennisfrank** [comment] 2017-08-23 14:31
@benjamminf Is multi level reordering still planned for the Craft 2 version?

**Comment by gabrielmoreira** [comment] 2017-10-05 04:56
I really appreciate this feature.

But as an alternative, would not it be easier to have a COPY and PASTE option, using the same behavior as duplicate?

**Comment by theskyfloor** [comment] 2017-10-05 11:38
Copy/paste would be huge - great idea! Perhaps it is easier to implement a gate if a block isn't assigned to a parent block as well?

**Comment by benjamminf** [comment] 2017-10-05 23:13
Man, I really need to find the time to make a new version release! I actually have copy/paste functionality done, and have fixed a lot of other issues. It's all on the [dev](https://github.com/benjamminf/craft-neo/tree/dev) branch – [download the plugin](https://github.com/benjamminf/craft-neo/archive/dev.zip) from there and try it out. Make sure you back up your database first.

Just a little general update: as you may have noticed, development on Neo and my other plugins has been almost non-existent for a while now. To be transparent, I've been completing a CS degree and working, both full time, which has been the cause for this. Thankfully I'm a few weeks away from graduating 🎉  so after that I'll be back into developing Neo for both Craft 2 and 3. Since a lot of you use this plugin I felt you deserve some kind of update.

**Comment by benjamminf** [comment] 2017-10-05 23:21
@dennisfrank at this point I don't think it's going to happen for Craft 2, at least yet. The reason it hasn't happened yet is because it would require a big rebuild of the UI to accommodate it, and with Craft 3 coming up I'd rather focus my efforts on that.

What *might* happen is the new UI being built for Craft 3 being back-ported to the Craft 2 compat version.

**Comment by theskyfloor** [comment] 2017-10-06 00:03
Congrats on your upcoming graduation!

**Comment by theskyfloor** [comment] 2017-10-06 00:12
Copy/paste works very very well. Thanks for the dev branch tip!!

**Comment by Nav33d** [comment] 2018-01-05 09:43
Hey @benjamminf I was wondering if it is possible to use the drag and drop patch with the latest 1.5.0 release?

**Comment by vandres** [comment] 2019-01-11 12:44
Hi @ttempleton 2.1.0 is out, what is the status of this issue?

**Comment by ttempleton** [comment] 2019-01-12 14:57
Hi @vandres, sorry that this did not make 2.1.0.  We definitely still plan to work on this, but at the moment our focus is on wrapping things up with the Craft 2 version and then implementing project config support for Craft 3.1.  Once we've finished those tasks, we'll be able to proceed with work on this feature.

**Comment by ttempleton** [comment] 2019-03-02 05:20
The `feature/multilevel-drag-sort-neo-2` branch now includes the work on the feature originally written for the Craft 2 version up to the point that @benjamminf made [this comment](https://github.com/spicywebau/craft-neo/issues/27#issuecomment-228588812) (i.e. multilevel dragging works, without restrictions on dragging blocks where they don't belong).

There is further work to include from the old `feature/multilevel-drag-sort` branch (the work from the last four commits), which hasn't been included at this time due to it involving a rethink of how to implement restrictions and therefore, as mentioned in [this comment](https://github.com/spicywebau/craft-neo/issues/27#issuecomment-237731745), multilevel dragging is not active.  That work will be included and hopefully completed some time in the near future, but in the meantime, anyone wanting to try out multilevel block reordering in Neo 2 should grab it from https://github.com/spicywebau/craft-neo/tree/c3eeca1d7539e38d98c8f2f2d60d9a6ef51f1590 (if you just want the updated JS it's located at `src/resources/main.js`).

**Comment by ttempleton** [comment] 2019-03-02 10:20
Update: Ben's progress on adding restrictions has now been ported to Neo 2 in the `feature/multilevel-drag-sort-neo-2` branch.  If anyone would like to try it out, it's recommended that you grab the branch's [`src/resources/main.js`](https://raw.githubusercontent.com/spicywebau/craft-neo/feature/multilevel-drag-sort-neo-2/src/resources/main.js) file (as long as you're on Neo 2.2.5 there shouldn't be any compatibility issues).

**Comment by vandres** [comment] 2019-03-02 18:41
@ttempleton Thank you. I will test it next week

**Comment by vandres** [comment] 2019-03-04 02:12
@ttempleton My first quick test looks very promising!

**Comment by ttempleton** [comment] 2019-03-09 08:15
Good to hear, @vandres!

From what I can tell, it's mostly functional, except that block types' max child blocks settings are not enforced (also the max top-level blocks field setting coming to Neo 2.3).  We'll continue working on it and testing it, though, and hopefully this will be ready for release soon.

**Comment by vandres** [comment] 2019-03-09 14:25
@ttempleton That would be great, thank you

**Comment by 23d1** [comment] 2019-03-11 20:06
Also tested, and seems to work! 🎉

**Comment by vandres** [comment] 2019-08-22 18:59
@ttempleton @pvldigital What is the state of this issue? It always gets postponed...

**Comment by ttempleton** [comment] 2019-08-22 22:17
Hi @vandres,

I opened pull request #222 a little while ago with more progress on this feature.  I've parted ways with @spicywebau since my last comment on this issue, so I can't give you an idea of when they'll complete and release this feature, sorry; but as a Neo fan, I, too, am looking forward to this feature being released!

**Comment by vandres** [comment] 2019-08-22 22:20
@ttempleton oh, sorry to hear. I hope you are fine?! Then lets hope somebody else take it up at @spicywebau

**Comment by pvldigital** [comment] 2019-08-22 22:40
Hi @vandres,

We're still looking into implementing multi level orders. It's just been slow because of the craft 3.2 update and the issues that arises from it.

@ttempleton i'll have a look at the PR soon.

**Comment by ttempleton** [comment] 2019-08-23 01:04
@pvldigital Thanks!

@vandres Thanks for your concern!  I am fine; to clarify, I returned to studying and decided to focus on that for a while.

For now, [I've set up a branch on my Neo fork](https://github.com/ttempleton/craft-neo/tree/multilevel-drag-sort-testing) with the updates from #222 merged in with the latest version of Neo for Craft 3.2.  If you'd like to try out the updates from #222, similar to my updates from earlier in the year, you should be able to grab [`src/resources/main.js`](https://github.com/ttempleton/craft-neo/blob/multilevel-drag-sort-testing/src/resources/main.js) from there and drop it into any Neo 2.4.4 installation.

**Comment by pvldigital** [comment] 2020-01-29 00:05
Hi all,

This feature has now been added in 2.6.0 (the update for craft 3.4.0).

**Closed by pvldigital** 2020-01-29 00:05 UTC
Labels: feature

**Comment by vandres** [comment] 2020-01-29 07:59
Woohoo, thanks! :D
