### ISSUE TITLE
Uncaught TypeError: Craft.MatrixInput is not a constructor and similar

### ISSUE THREAD

**Issue by superflausch** [spicywebau/craft-neo#793] opened 2023-09-27 12:25 UTC
### Bug Description

Recently we get JS errors on different fields as soon as they are added to an newly created entry (doesn't seem to affect existing entries). Those field are nested in a NEO field.

I first thought this is a Craft issue related to a newer update and reported it there. But per Brandon's [comment/commit](https://github.com/craftcms/cms/commit/8696f5bd744d2cacef2150bcbb6660e57b4e1ce9) this is more likely a NEO issue. Original issue is [#13752](https://github.com/craftcms/cms/issues/13752).

Here are some examples:

```
VM4487:376 Uncaught TypeError: Craft.MatrixInput is not a constructor
    at <anonymous>:376:19
    at m (jquery.js?v=1695796812:2:867)
    at Pe (jquery.js?v=1695796812:2:48869)
    at w.fn.init.append (jquery.js?v=1695796812:2:50073)
    at s.constructor.initUi (Block.js:342:18)
    at s.constructor.addBlock (Input.js:314:11)
    at e (Input.js:1110:12)
    at Input.js:1149:9
```

```
VM4506:60 Uncaught ReferenceError: CKEditor5 is not defined
    at <anonymous>:60:3
    at <anonymous>:61:3
    at m (jquery.js?v=1695796812:2:867)
    at Pe (jquery.js?v=1695796812:2:48869)
    at w.fn.init.append (jquery.js?v=1695796812:2:50073)
    at s.constructor.initUi (Block.js:342:18)
    at s.constructor.addBlock (Input.js:314:11)
    at e (Input.js:1110:12)
    at Input.js:1149:9
```

The errors prevent some fields to work properly. After saving the entry, it can be edited without an issue and without those errors. 

This happens on multiple sites which share a similar setup with a NEO field. But seems to be isolated to sites running NEO versions after 3.8.6 (and also Craft versions newer than 4.5.3). Or in other words a site running Craft 4.5.3 and NEO 3.8.6 sharing the same field etc. setup is working without this issue.

### Steps to reproduce

1. Create a new entry (which uses this field setup)
2. Add a new or multiple blocks
3. Console throws those errors, some field don't work properly

### Expected behaviour

No errors, fields work properly

### Neo version

3.9.3

### Craft CMS version

4.5.6

### Does this issue involve templating, and if so, is eager-loading used?

No.

**Comment by ttempleton** [comment] 2023-09-27 12:44
Duplicate of #790

**Closed by ttempleton** 2023-09-27 12:44 UTC
Labels: bug
