### ISSUE TITLE
Blocks appearing on the front end but not in the editor field

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#459] opened 2021-05-27 22:34 UTC
#### Description
I have a page on my site that is showing blocks on the front end that I remember setting up yesterday, but when I look at the page in the CP editor some of the blocks are not appearing in the Neo field. I'm not sure about steps to reproduce. I saved the fields as one would normally and everything was working fine, but now the blocks don't show up in the Neo field even though they are still rendering on the front end and in the live preview. If I create a new draft then the blocks don't render in the live preview. I also cannot create any new blocks on the home page entry. I also tried removing the home page entry and creating a new page entry with the same content and I'm encountering the same problem. I can provide a project config and database backup if needed.

#### Steps to reproduce
1.
2.
3.

#### Other information
- Neo version: 2.9.9
- Craft version: 3.6.15
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used? yes.

**Comment by brianrivet-tilt** [comment] 2021-05-28 04:14
To expand on this, I am not able to add blocks to any of my pages now. I've also tried using the clone and delete block features and they aren't working either.

**Comment by ttempleton** [comment] 2021-05-28 10:30
Are there any JavaScript errors in your console (either on page load or when you try to add/clone/delete a block)?

**Comment by brianrivet-tilt** [comment] 2021-05-28 12:18
Here's what I get when I try to clone or delete an existing block.:

Uncaught TypeError: Cannot read property 'getId' of undefined
    at main.js?v=1621553702:14
    at Array.find (<anonymous>)
    at N (main.js?v=1621553702:14)
    at s.constructor.updateMenuStates (main.js?v=1621553702:14)
    at s.constructor._updateButtons (main.js?v=1621553702:13)
    at s.constructor.addBlock (main.js?v=1621553702:13)
    at s (main.js?v=1621553702:13)
    at Array.<anonymous> (main.js?v=1621553702:13)
    at C (velocity.js:4563)
    at T (velocity.js:4461)

When it comes to adding a completely new block, it lets me add it and do everything normally, but if I save it and then come back to the page, the blocks I added are no longer there.

**Comment by ttempleton** [comment] 2021-05-28 12:57
That looks like the same error as #452 (but I'm going to close that issue and continue with this one instead).  I'm still unable to reproduce the error in my usual testing environment, though; could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au and we'll look into it.

**Comment by brianrivet-tilt** [comment] 2021-05-28 14:06
I've sent the database and the composer file. Let me know if you need anything further from me.

**Comment by brianrivet-tilt** [comment] 2021-06-01 14:19
Hi, I just wanted to check in and verify if you got the composer file and database backup I sent and also see if you were able to find anything. Thanks!

**Comment by ttempleton** [comment] 2021-06-02 05:18
Thanks for sending those.  Unfortunately I’m still unable to reproduce the error (under normal circumstances) even with those, and it definitely doesn’t seem like any blocks are disappearing from the editor.

I’ve been looking through the code to figure out where the `undefined` in the error could be coming from, and at the moment I think it’s happening when Neo [tries to find a block type's child block types by their handle](https://github.com/spicywebau/craft-neo/blob/2.9.10/client/src/input/Input.js#L401).  If I force that to always return `undefined`, then trying to copy a block gives me the exact error as seen in #452, and then reloading the page gives me an error that looks similar to yours.  So I think there’s some invalid block type data getting through somehow.  I’ll keep looking and will let you know if I have any more questions about that.

I’m not sure whether the blocks disappearing is related to that error or not, though.  If you test in another browser or a private/incognito window so you don’t have any copied block data (since [the exact line of code where the error occurs](https://github.com/spicywebau/craft-neo/blob/2.9.10/client/src/input/Block.js#L851) is in a loop over the copied blocks to determine whether the paste menu option should be enabled), edit an entry without copying a block (cloning should still be okay), do new blocks still disappear?

**Comment by brianrivet-tilt** [comment] 2021-06-02 15:42
I tried it with an incognito window and it works as it should. New blocks are added just fine and remain in the pages in the cp editor.. Cloning works as well. I'll see if incognito does anything with regard to the blocks not showing up.

**Comment by brianrivet-tilt** [comment] 2021-06-02 15:52
I don't know if this helps, but I created a couple of new blocks in my home page entry in the incognito window and the new blocks stayed after the page was saved and they appeared on the front end. If I open the site in a non-incognito window the blocks are showing up on the front end, but when I view the edit entry screen in the CP the blocks I added in the incognito window are not there.

**Comment by ttempleton** [comment] 2021-06-03 10:29
Thanks @brianrivet-tilt.  I've since been able to reproduce the error, and narrowed down the bug to the Neo field configuration editor not updating the values of new block types on the child block type checkboxes if their handles were only ever auto-updated as a result of the block type's name being updated, never updated directly.  That means any block type that has the new block type as a child will store an empty string in its child block types instead of the new block type's handle, which then causes the JavaScript error.

I should have a fix released in the next day, but as a temporary workaround, resaving the Neo field should make the error disappear.

**Comment by ttempleton** [comment] 2021-06-04 03:38
This should now be fixed in Neo 2.9.11.

**Closed by ttempleton** 2021-06-04 03:38 UTC
Labels: bug, has workaround
