### ISSUE TITLE
Integrity constraint violation 'sortOrder'

### ISSUE THREAD

**Issue by JshGrn** [spicywebau/craft-neo#754] opened 2023-06-13 14:36 UTC
### Bug Description

Upgraded a site from Neo 2.9.11 to 2.13.18 and now when a Entry is saved that contains a Neo field we get

`Integrity constraint violation – [yii\db\IntegrityException](http://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html)
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'sortOrder' in order clause is ambiguous`

The query runs fine if 'sortOrder' becomes 'neoblocks.sortOrder' within subquery

### Steps to reproduce

Save any Entry that contains a neo field with changes 

### Neo version

 2.13.18

### Craft CMS version

3.8.13

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by JshGrn** [comment] 2023-06-13 15:20
I just stepped though on the latest version of Craft version by version of Neo to find out where the issue is introduced and it is introduced on 2.12.1

**Comment by JshGrn** [comment] 2023-06-15 11:50
@ttempleton Hi sorry to tag you here but it would be great if you could review the above so that I can get the site updated on production.

**Comment by ttempleton** [comment] 2023-06-15 12:37
Hmm, not sure why that's caused that error for you as it worked fine for me. But it doesn't hurt to make that change anyway, so that should be fixed now in 2.13.19.

**Closed by ttempleton** 2023-06-15 12:37 UTC
Labels: bug

**Comment by JshGrn** [comment] 2023-06-15 12:39
Perfect thank you, maybe a different SQL version? This is using MariaDB 10.3. The issue comes from the join of the elements table which also has a sortOrder

**Comment by JshGrn** [comment] 2023-07-25 09:23
This is back for me in the latest version of Neo bizarrely, there was a missed line in the same file as the previous fix.

https://github.com/spicywebau/craft-neo/blob/272b7872e87c14c294ef3552154f78e8e33d2f8e/src/Field.php#L1312

**Comment by ttempleton** [comment] 2023-07-25 11:55
Yeah, that change was intentionally reverted in the Craft 4 version as it caused a different error. Since the `elements` table isn't supposed to have a `sortOrder` column, and assuming that's still the cause of your error, we're not going to reintroduce that change, and you'll need to investigate why your `elements` table has a column that it shouldn't have. Please let me know if that isn't the cause of it in this case, though.
