### ISSUE TITLE
Display error with dropdown button

### ISSUE THREAD

**Issue by timprint** [spicywebau/craft-neo#468] opened 2021-06-19 19:03 UTC
#### Description
I have a large NEO field that I am using for lots of sections. It's still in development but we have been using it to add content for several months. It's been working well. I recently did some Craft and plugin updates (everything is on the latest versions now) and the nested block dropdown in the NEO field is not displaying properly.

If you start with a wide viewport and all the buttons can display side by side it works.
![Screenshot 2021-06-19 at 19 54 24](https://user-images.githubusercontent.com/365760/122652753-50dd8280-d138-11eb-89ca-78c671b6ed4d.png)
When you resize the screen the dropdown block doesn't resize. It get's cut off on the right so you can't access the last dropdowns.
![Screenshot 2021-06-19 at 19 55 58](https://user-images.githubusercontent.com/365760/122652772-736f9b80-d138-11eb-85ed-52612d45fa45.png)
If you load the page in a narrow viewport, the dropdown appears OK but when you open it you get the following:
![Screenshot 2021-06-19 at 19 58 27](https://user-images.githubusercontent.com/365760/122652813-bc275480-d138-11eb-9362-73d065c697fc.png)

I'm not getting any Console errors.
The h6 and ul elements are not getting added for some reason.
![Screenshot 2021-06-19 at 20 00 57](https://user-images.githubusercontent.com/365760/122652891-348e1580-d139-11eb-9d71-dedf4444440e.png)

- Neo version: 2.10.2
- Craft version: 3.6.17

**Comment by ttempleton** [comment] 2021-06-21 02:11
Thanks for reporting that bug with the dropdown content display -- that was caused by a change in Neo 2.10.0 and should now be fixed in 2.10.3.

Regarding the buttons being cut off when reducing the window size, instead of reverting to the dropdown: I've just done some testing with Neo and Matrix fields and noticed this happening in both cases (it seems to start working after you increase and then reduce the window size again) so I think that is a Craft bug affecting both field types.  I'll be happy to reopen this issue if there's any fix required for that on Neo's end, though.

**Closed by ttempleton** 2021-06-21 02:11 UTC

**Comment by timprint** [comment] 2021-06-21 08:58
Confirmed fixed in 2.10.3. Thanks for the quick response.
