### ISSUE TITLE
Update destroys Neo structure and deletes elements

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#317] opened 2020-03-23 09:39 UTC
#### Description
I just updated a site to the new Neo version. I was aware of the warning, that there could be changes in the structure, therefore I checked all pages. On almost all of the pages, the order of the blocks changed. This was already difficult to fix, since it is a multi-language site and I do not speak all those languages. "Re-saving the page" as mentioned in the notes did not restore the page. I had to rearrange by hand.

However, on at least one site, some of the elements were actually deleted and could not be changed. This was on a page with quite a nested structure. 
Rolling back to version 2.6.5.1 restored everything, but that's not a permanent solution, obviously. 

#### Other information
- Neo version: v2.7.1.1
- Craft version: 3.4.10.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: yes
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: only save to site they were created in
- Is eager-loading used? No

**Comment by pvldigital** [comment] 2020-03-23 21:29
Hi @luke-nehemedia,

The issue is probably because the `structureId` wasn't set when querying the blocks. I have added the it to the element query so could you try it again?

**Comment by pvldigital** [comment] 2020-03-23 21:34
Also when updating neo, did the migration of the `sortOrder` field get processed? The order issue sounds like the `sortOrder` value wasn't set correctly.

**Comment by pvldigital** [comment] 2020-03-24 00:21
@luke-nehemedia thanks to @Mosnar (issue #315), a fix has been made for the migration file which should fix up the sort order issue

**Comment by luke-nehemedia** [comment] 2020-03-24 14:10
I just tried it again and this time everything works fine! 

Thank you for your help.

**Closed** 2020-03-24 14:10 UTC
