### ISSUE TITLE
Issue with GraphQL query on 3.5.10

### ISSUE THREAD

**Issue by sietsedeglee** [spicywebau/craft-neo#689] opened 2022-12-08 09:45 UTC
#### Description
On Neo 3.5.10 I'm running into an issue that GraphQL queries do not return nested relations anymore, but instead return top level empty object values. Seems to be an issue with flattening?

#### Steps to reproduce
1. Query a nested relationship in a Neo field:
```
contents {
  ... on contents_step_BlockType {
    id
    display_title
    interventionContent: children {
       # this level is always empty as of 3.5.10
    }
  }
}
```

#### Other information
- Neo version: 3.5.10
- Craft version: 4.3.4
- Is eager-loading used? n/a > GraphQL
- Workaround: downgrading to 3.5.9

**Comment by ttempleton** [comment] 2022-12-08 09:50
Closing this issue as a duplicate of https://github.com/spicywebau/craft-neo/issues/685

**Closed** 2022-12-08 09:50 UTC
