### ISSUE TITLE
Inconsistent Neo block child fields "Selectable Entries Condition" behavior

### ISSUE THREAD

**Issue by joelod** [spicywebau/craft-neo#796] opened 2023-09-29 15:45 UTC
### Bug Description

Entry field's "Selectable Entries Condition" when inside a Neo block won't update if it looks for another field (in this case also an entry field) on the Neo parent entry. It only updates this if I actually save the entry (and the page refreshes), even if validation errors exist (like unfilled required fields).

I'll try to better explain this with an example on the "Steps to reproduce".

Important info for this example:

**Selectable Entries Condition** (for the entry field "film")
Related Edition: is related to: {owner.relatedEdition[0].id}

### Steps to reproduce

1. Add a new entry in "programmeEntries"
2. Select an entry in the "relatedEdition" field (for example, "Edition 15")
3. Add a new block in the Neo field "Sessions"
4. Inside this Neo block, select an entry in the "film" field (for example, "Oldboy")
5. The modal box to select an entry, shows me every "filmEntries" entry that exists, instead of just the ones from the "Edition 15"

### Expected behaviour

When adding a new Neo block, a child field of this block should obtain the latest draft of this entry in its "Selectable Entries Condition", instead of the last non-draft version of this entry on the database. This is what happen to other Neo blocks that already existed when the entry was last saved.

### Neo version

3.8.6

### Craft CMS version

Pro 4.5.6.1 

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2023-10-02 03:06
Does this work as expected if you try it with a Matrix field?

**Comment by joelod** [comment] 2023-10-03 23:00
> Does this work as expected if you try it with a Matrix field?

Thanks.

Just tried it out, it does have the same issue with Matrix. Looks like this is an issue that is being inherited from Matrix, and the bug should be reported in the CraftCMS repo?

**Comment by ttempleton** [comment] 2023-10-04 12:22
Yeah, we'd be inheriting it either through Craft functionality beyond Matrix/Neo fields, or through Matrix code that's been reused in Neo.

To be honest, I'm not sure if it would be a bug or the intended behaviour, since it could be argued that it's selecting the published entry and that it's accurate as far as that is concerned - but also I agree that it makes sense to represent the current state of the provisional draft if it's the entry you're editing.

I'd recommend opening either a bug report or a discussion on the Craft repo to get clarity on that - but we definitely want to be consistent with Matrix behaviour for this, so if they judge it to be a bug and there's a separate change required in Neo to fix it there, we'd be happy to do so.

**Comment by ttempleton** [comment] 2023-10-27 01:11
Going to close this for now - per the above comment, the Neo behaviour is currently consistent with Matrix, and this is a case where we want consistency between the two field types.

**Closed by ttempleton** 2023-10-27 01:11 UTC
Labels: bug
