### ISSUE TITLE
Can't edit Neo field after update to Craft 3.7

### ISSUE THREAD

**Issue by diluno** [spicywebau/craft-neo#479] opened 2021-07-14 13:34 UTC
#### Description
I have a Neo field with various blocks, most of them have only one field in them. (sometimes Super Table fields)

Yesterday I updated to Craft 3.7. If I now add a field inside a Neo block, and then fill out this field on an entry, it takes ~10 seconds to save the page. And then the whole Neo field is empty.

#### Steps to reproduce
1. Add fields to Neo block
2. Fill out field in entry
3. Save entry
4. Field is empty

#### Other information
- Neo version: 2.11.0
- Craft version: 3.7.0
- (if multi-site) What is the affected Neo field's propagation method: "Save blocks to all sites the owner element is saved in"
- Is eager-loading used? I don't know

**Comment by diluno** [comment] 2021-07-14 13:43
It also happens when I add a new block to the Neo field.

**Comment by palomamtnez** [comment] 2021-07-14 20:13
I second this. Having the same issue with Craft 3.7

**Comment by brandonkelly** [comment] 2021-07-15 00:15
I was hoping to find time to look into this today, but not looking like that will happen unfortunately.

@ttempleton If you have a chance to look into it, please feel free to DM me on Discord if I can help. Every change I made to Matrix-related stuff in 3.7 was supposed to be backwards-compatible, but I may have overlooked something.

**Comment by ttempleton** [comment] 2021-07-15 08:56
Thanks for reporting this!

@diluno in addition to your observations, this was happening when I saved the entry before the provisional draft could autosave after a change to the Neo field's content.  I tracked it down to a bug that was causing the published block IDs to be reused for the blocks being created for the new entry revision, and that should now be fixed in Neo 2.11.1.

@palomamtnez I was unable to reproduce the behaviour from your other issue, but the Neo content loss definitely could've been caused by this bug, so hopefully that's fixed now.  I'm unsure if this bug would've caused the entry to lose its position in the structure section, but if that was related, then hopefully that's fixed now too.

Appreciate the offer @brandonkelly, but this was definitely a Neo bug!

**Comment by diluno** [comment] 2021-07-15 09:10
Thank you so much @ttempleton!

**Comment by diluno** [comment] 2021-07-15 09:15
@ttempleton 

I added a new field to a block, tested it locally - everything worked.
But when I deployed to my staging server, applied the project config and filled out the field again, it cleared the whole Neo field again.

Could you reopen this issue?

**Comment by ttempleton** [comment] 2021-07-15 09:34
Sure.  I'm unable to reproduce the content clearing, so there must be something I'm missing regarding field configuration.  If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au along with any instructions that may be helpful (e.g. if there's a section or entry in particular being affected) and we'll have a look at it.

**Comment by diluno** [comment] 2021-07-15 09:45
I re-added the field, rebuilt my project config and now I can't reproduce it anymore either. 😕

I guess you can close it again, sorry! I'll let you know should it happen again. Thank you so much!

**Comment by ttempleton** [comment] 2021-07-15 10:26
No worries @diluno -- glad it's working now, but please do let us know if that happens again!

**Closed by ttempleton** 2021-07-15 10:26 UTC
Labels: bug
