### ISSUE TITLE
Neo Blocks being deleted

### ISSUE THREAD

**Issue by spib** [spicywebau/craft-neo#532] opened 2022-01-21 17:00 UTC
#### Description
We're seeing a strange situation where an entry is saved with no error, but when you go back into the entry the neo field is empty. Looking in the database, there are new rows being added to `craft_neoblocks` but the associated `craft_elements` record has a `dateDeleted` value, so it seems like the rows are created and then immediately deleted.

This is happening consistently on our production server, but the same database & code locally work fine.

#### Steps to reproduce
1. Add a Neo Field containing one block type which has one field of type LinkField (https://github.com/sebastian-lenz/craft-linkfield) 
2. Add 3 or 4 blocks
3. Save the entry

#### Other information
- Neo version: 2.12.2
- Craft version: 3.7.26
- (if multi-site) What is the affected Neo field's propagation method: None
- Is eager-loading used? No

**Comment by ttempleton** [comment] 2022-01-24 06:00
I'm unable to reproduce this so far but I have a few questions:

- Is this happening on any entry or just one specific entry?
- Does this also happen with Neo block types that don't use a link field?
- If you add a Matrix field with a block type that uses a link field, does that work as expected?

**Comment by spib** [comment] 2022-01-25 19:09
Sorry for the delay in getting back to you

* It seems like it's all entries in a particular section
* We don't have any other neo fields on that section without link fields so hard to say
* Same problem happens with a matrix field configured with a link field

Does this suggest it's a Craft issue rather than Neo?

**Comment by ttempleton** [comment] 2022-01-27 04:15
I think so, but I'll recommend trying another test with the same Matrix field and a block type that doesn't have a link field. If the blocks still disappear, then that does sound more likely to be a Craft issue that affects block element fields in general. If they don't disappear, then the link field plugin may be doing something to interfere with Matrix and Neo block saving.

Will close this issue for now, but will reopen if the Neo situation turns out to be separate to what's happening with Matrix.

**Closed by ttempleton** 2022-01-27 04:15 UTC
