### ISSUE TITLE
Neo blocks lose nesting on preview

### ISSUE THREAD

**Issue by shep-cc** [spicywebau/craft-neo#612] opened 2022-06-29 08:43 UTC
#### Description
When editing a page containing Neo blocks nested to level 3, activating Preview is flattening out the nesting, so all level 3 elements move to level 2.

#### Steps to reproduce
1. Create a page with Neo blocks nested up to or beyond 3 levels
2. Activate preview (and make an edit to be sure)
3. Close preview and save the page
4. Observe the block nesting

#### Other information
- Neo version: 3.1.5
- Craft version: 4.1.0.2
- Multi-site: Only save blocks to the site they were created in
- Is eager-loading used? No

**Comment by ttempleton** [comment] 2022-06-29 09:20
Unable to reproduce this, and not sure how it would've happened - if possible, could you please send your database backup and composer.json/lock files to plugins@spicyweb.com.au and we'll have a look.

**Comment by shep-cc** [comment] 2022-07-04 08:46
thanks for taking a look 🙂

**Comment by ttempleton** [comment] 2022-07-06 04:59
I've just released Neo 3.1.6 which should fix this (Neo was finding the wrong structure ID for a block structure when creating a provisional draft from an entry, because the site ID wasn't being set on the structure ID query). I'll close this issue for now, but please let me know if there are still any block level issues with the new version.

**Closed by ttempleton** 2022-07-06 04:59 UTC
