### ISSUE TITLE
Error "Invalid owner ID" on saving some entries with Neo field

### ISSUE THREAD

**Issue by twosixcode** [spicywebau/craft-neo#280] opened 2019-10-31 14:30 UTC
#### Description

Updated Craft from 2 to 3. In Craft 3, on _some_ entries (not all), we get the following error when attempting to save the entry:

> Invalid owner ID: 23911
 
Some other, very similar entries in the same Section will save just fine. 

We are able to take a non-saving entry and "Save as New Entry" and it works without issue. The new entry does not have the Invalid owner ID error on entry-save. 

We are also able to save the entries just fine if we change the Neo field's propagation method to "Only save blocks to the site they were created in."

#### Steps to reproduce
Not sure how easy it will be for you to reproduce this, but we believe it may be related to the update from Craft 2 to 3, and possibly to multi-site.  

#### Other information
- Neo version: 2.5.3
- Craft version: 3.3.8
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: 
  Yes, the fields were marked as "translatable" in Craft 2 and are marked as managed on a per-site basis in Craft 3.
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: 
  Save blocks to all sites the owner element is saved in.
- Is eager-loading used? 
  No

Thanks for any help you are able to provide!

**Comment by pvldigital** [comment] 2019-10-31 21:19
Hi @twosixcode,

Can you send me the web log and composer.json files to plugins@spicyweb.com.au after receiving the error? It's going to be difficult to debug but i'll see what I can do.

**Comment by twosixcode** [comment] 2019-11-04 23:08
Thanks for the reply! I sent a copy of web.log and composer.json.

**Comment by pvldigital** [comment] 2019-11-05 21:17
Hi @twosixcode,

I had a look at the web.log and it looks like it has something to do with the matrix field/block missing its owner id.

Can you give me more info on how it's laid out? e.g is there a matrix field within neo or does the entry have a matrix field separate from neo?

**Comment by twosixcode** [comment] 2019-11-05 22:18
Thanks. Yes, there are a 6 Matrix fields that are available for use in this particular Neo field layout (they are part of the Neo field). The Neo field layout includes 26 total block types. Some of those are used only as child blocks (not top level). I can provide a screenshot of the field settings, highlighting the block types that involve a Matrix field. Or is there a more useful format to provide more information for you?

More importantly! ... I disabled Blitz and ran a test now and everything re-saved fine, even with the Propagation set back to the originally problematic "Save blocks to all sites the owner element is saved in." It appears that Blitz is a factor here. 

We're not really blocked on this, because setting the Propagation on this Neo field to "Only save blocks to the site they were created in" allows us to save just fine with Blitz enabled. But if this is a compatibility issue with Blitz, or there is some other cause, we'd love help get to the bottom of that if we can.

**Comment by pvldigital** [comment] 2019-11-05 22:40
Hmm I wonder if the issue is with the cached pages after upgrading to craft 3. Did you try fully clearing the cache and warming it again?

**Comment by twosixcode** [comment] 2019-11-05 22:42
See my edit to my previous comment. I'm having trouble even reproducing the original issue now. So seeing all the saves run fine with Blitz disabled may have been a red herring. 

We've been actively working on this site right now so things are a bit in flux and I find I'm now unable to reproduce the original Invalid OnwerId issue, even though when I posted issue originally it was consistent. I will post more detail once I can reproduce the issue again and narrow things down a bit more.

**Comment by pvldigital** [comment] 2019-11-05 22:45
Ah okay no worries. Let me know once you're able to reproduce it.

**Comment by pvldigital** [comment] 2019-11-13 01:24
Hi @twosixcode,

I'm going to close this issue for now. If it reoccurs or more information can be provided please comment and i'll reopen this.

**Closed by pvldigital** 2019-11-13 01:24 UTC

**Comment by twosixcode** [comment] 2019-11-13 01:50
Thanks. Yeah, I haven't been able to turn to it again and create the same conditions where it might arise. As I mentioned earlier, much in flux, so might not even crop up again. If I do, I will reopen. I appreciate it.
