### ISSUE TITLE
Neo Block Fields not stored

### ISSUE THREAD

**Issue by superflausch** [spicywebau/craft-neo#296] opened 2020-01-31 15:48 UTC
#### Description

Somehow after the latest updates (Craft 3.4.1 / Neo 2.6.0) I'm not able to save the contents of Neo blocks anymore. The blocks themselves get created/stored but not the values/content of the fields within. This happens on updated or on initial creation of entries. The admin panel displays the "Entry saved." message, I don't see any errors or related entries in my logs.

The same site worked without issues prior to updating (Craft 3.4.0 / Neo 2.5).

Any ideas?

#### Steps to reproduce
1. Edit entry
2. Change a value within a Neo block
3. Save entry

#### Other information
- Neo version: 2.6.0
- Craft version: 3.4.1
- no multi.site
- Is eager-loading used? Nope.

**Comment by pvldigital** [comment] 2020-01-31 19:43
Hi @superflausch,

I've been testing it myself with the latest version of craft and I'm unable to recreate the issue, blocks and the field data is successfully saved.

Are you using any non standard field plugins?
Is project.yaml usage enabled?

**Comment by superflausch** [comment] 2020-01-31 20:07
Strange thing is that this worked with Craft 3.4-RC and Neo 2.5.9/10 prior to the latest updates. The only other plugin, which got updated was Freeform. Disabling it doesn't help.

Yes, project.yaml usage is and was enabled.

Those are all the plugins activated right now:
AsyncQueue | 2.0.0
Control Panel CSS | 2.2.0
Embedded Assets | 2.1.1.1
Freeform | 3.6.1
Imager | v2.3.1
Imager Pretransform | 2.0.3
Minify | 1.2.9
MJML | 1.0.2
Neo | 2.6.0
Obfuscator | 1.0.3
PDF Transform | 1.0.2
Redactor | 2.5.0
SEO | 3.6.3
Table Maker | 2.0.1
Typed link field | 2.0.0-beta.6

**Comment by hatzipanis** [comment] 2020-02-01 23:50
Also seeing this behaviour. Existing Neo field content is still there but no new data is being saved unfortunately.

- Craft CMS 3.4.2
- Neo 2.6.0

**Comment by pvldigital** [comment] 2020-02-02 00:14
Hi @hatzipanis, are you also using the same plugins listed by @superflausch.

Can you both also see any errors in the browser console?

**Comment by superflausch** [comment] 2020-02-03 08:30
I don't see any warnings in the browser console log or in the craft logs.

I'm able to add, remove or disable the blocks themselves, but what ever field I change within those blocks just gets lost.

Also updating to Craft 3.4.2 doesn't help.

**Comment by besimhu** [comment] 2020-02-03 18:34
I am also having this issue. It is definitely not related to other plugins. I had to switch back down to `2.5.10` in order for fields to save again. I am on 3.4.2 of Craft.

As with @superflausch I am experiencing the same.

**Comment by pvldigital** [comment] 2020-02-03 19:56
Strange I still haven’t been able to replicate the issue. 

Can you send me a copy of your composer.json + lock file and if possible a copy of the database? You can send it to plugins@spicyweb.com.au.

Also what php version are you using?

@hatzipanis @superflausch @besimhu

**Comment by superflausch** [comment] 2020-02-03 20:04
Thanks. Just sent you the files by mail.

I see this behaviour on PHP 7.4.1 and 7.3.14.

**Comment by pvldigital** [comment] 2020-02-03 22:56
@superflausch Thanks for files. I'm pretty sure I know the cause of this now and have applied a fix.

@besimhu @hatzipanis Did you name your neo field as 'blocks'?

**Comment by besimhu** [comment] 2020-02-04 00:23
@pvldigital  I sure did

**Comment by pvldigital** [comment] 2020-02-04 00:33
@besimhu yep thanks for confirming. A fix will be released for this issue in a bit.

**Comment by pvldigital** [comment] 2020-02-04 04:07
Hi All,

A release has been made for this issue, v2.6.1.

@superflausch @hatzipanis @besimhu

**Comment by hatzipanis** [comment] 2020-02-04 19:07
@pvldigital thank you so much! Will give this a run today.

**Comment by hatzipanis** [comment] 2020-02-05 01:05
Working perfectly thank you @pvldigital 

**Other information**

Neo version: 2.6.1
Craft version: 3.4.4

**Comment by pvldigital** [comment] 2020-02-05 01:37
@hatzipanis awesome, good to know it's working for you.

---

I'll be closing this issue for now, if there's any issues it can be reopened.

**Closed by pvldigital** 2020-02-05 01:37 UTC

**Comment by superflausch** [comment] 2020-02-05 08:04
Works fine now. Thanks a lot.

**Comment by besimhu** [comment] 2020-02-06 16:13
@pvldigital  yes, thank you for the fix. It is appreciated.
