### ISSUE TITLE
Cannot assign string to property benf\neo\models\BlockType::$fieldId of type ?int

### ISSUE THREAD

**Issue by edoardolunardi** [spicywebau/craft-neo#646] opened 2022-09-02 08:43 UTC
#### Description
Whenever I try to create a field of type neo, I get the following error

`Cannot assign string to property benf\neo\models\BlockType::$fieldId of type ?int`

<img width="358" alt="Screenshot 2022-09-02 at 10 34 07" src="https://user-images.githubusercontent.com/34012860/188099940-b96ea222-0d40-4429-b2a3-1f27e29ee136.png">

The only way I can create a neo field now is by first creating the field with a different type, for instance plain text, and then switching it to neo type.

#### Steps to reproduce
1. In Craft, create a new field of type `neo`
2. The error appears, preventing the creation of the field

#### Other information
- Neo version: `3.3.6`
- Craft version: `4.2.3`

**Comment by ttempleton** [comment] 2022-09-02 09:35
I'm unable to reproduce this, but I suspect this wouldn't be a Neo issue, since Neo doesn't set its own field's IDs.

Assuming this is happening in `benf\neo\Field::setBlockTypes()`, a Neo block type's field ID [is set](https://github.com/spicywebau/craft-neo/blob/99a0458a7c02ba24eb2ed028d36a95a25fc68ccb/src/Field.php#L277) in the same way as [setting a Matrix block type's field ID](https://github.com/craftcms/cms/blob/2ee1ed6d8f413744b4c4e1455f5313a1103ef29c/src/fields/Matrix.php#L296) when setting a Matrix field's block types. [`craft\models\MatrixBlockType::$fieldId`](https://github.com/craftcms/cms/blob/2ee1ed6d8f413744b4c4e1455f5313a1103ef29c/src/models/MatrixBlockType.php#L36) also has type `?int`, so I'm guessing this error will occur when you try to create a new Matrix field as well.

I'll assume that's the case and close this issue, but let me know if this doesn't occur with Matrix and I'll reopen it.

**Closed by ttempleton** 2022-09-02 09:35 UTC
