### ISSUE TITLE
Adding new blocks throws "There was a problem getting the previous element." Error

### ISSUE THREAD

**Issue by r-anwar** [spicywebau/craft-neo#967] opened 2024-11-18 14:01 UTC
### Bug Description

When an editor creates new blocks rapidly, the NEO plugin throws the following exception:

[web.ERROR] [yii\base\Exception] There was a problem getting the previous element. {"trace":["#0 /app/vendor/spicyweb/craft-neo/src/controllers/Input.php(136): craft\\services\\Structures->moveAfter()","#1 [internal function]: benf\\neo\\controllers\\Input->actionRenderBlocks()","#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#3 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#4 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()","#5 /app/vendor/craftcms/cms/src/web/Application.php(340): yii\\base\\Module->runAction()","#6 /app/vendor/craftcms/cms/src/web/Application.php(639): craft\\web\\Application->runAction()","#7 /app/vendor/craftcms/cms/src/web/Application.php(302): craft\\web\\Application->_processActionRequest()","#8 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest()","#9 /app/web/index.php(16): yii\\base\\Application->run()","#10 {main}"],"memory":55790784,"exception":"[object] (yii\\base\\Exception(code: 0): There was a problem getting the previous element. at /app/vendor/craftcms/cms/src/services/Structures.php:410)"}

This occurs when the loading icon of the previous block is still visible and the editor has already created a new block.

### Steps to reproduce

- Create a new block while the previous one is still loading, may several times.

### Neo version

4.2.14

### Craft CMS version

4.11.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by r-anwar** [comment] 2024-11-19 11:59
I updated to Neo version 4.2.21, still observing the error above.

**Comment by ttempleton** [comment] 2024-11-22 04:54
If possible, could you please send your composer.json/lock files and database backup to plugins@spicyweb.com.au, along with information about an entry where this is happening, and we'll have a look.

**Comment by ttempleton** [comment] 2024-11-27 09:27
Thanks for sending that in. Unfortunately I couldn't reproduce it there, but I'm guessing this generally involves some mixup with what the previous block actually is, if more than one is being created at the same time. We shouldn't really be allowing multiple block creation operations at the same time anyway, because of the possibility of issues like this, so I've made changes in the 4.x branch so that the new block buttons will be disabled while a new block is being created. I'll update here when the next release is tagged.

**Comment by r-anwar** [comment] 2024-11-27 09:51
Thank you for your quick reply. For your information, if I create a block and wait until the block is there and then create the next one, the error occurs as well. Nevertheless, I would try the update.

**Comment by ttempleton** [comment] 2024-11-27 22:24
That sounds like the update won't help, then. Would it be possible for you to make a screen recording of the issue and send that in by email? I feel like there's something I'm missing that a screen recording could help me understand.

**Comment by r-anwar** [comment] 2024-11-28 08:07
I just sent you the screen recording.

**Comment by ttempleton** [comment] 2024-12-02 08:38
Thanks for sending that, I can confirm receipt. We'll look further into that and I'll let you know when we have an update.

**Comment by ttempleton** [comment] 2024-12-09 11:04
This should be fixed now in 4.2.22, but let me know if issues persist and I'll reopen.

**Closed as completed by ttempleton** 2024-12-09 11:04 UTC
Labels: bug report, bug report status: fixed
