### ISSUE TITLE
Failed jobs in queue manager: Deleting old Neo blocks

### ISSUE THREAD

**Issue by anita-chouhan** [spicywebau/craft-neo#724] opened 2023-03-16 09:17 UTC
### Bug Description

**Description**

I am getting a failed job in the queue manager on deleting an entry. The entry contains a _Neo_ field with multiple blocks in it.

**Other information**
<img width="962" alt="Screenshot 2023-03-16 at 12 21 15 PM" src="https://user-images.githubusercontent.com/30666052/225537615-afc7def3-7fbd-424a-9b3a-adf7f0f1e511.png">

<img width="955" alt="Screenshot 2023-03-16 at 12 20 07 PM" src="https://user-images.githubusercontent.com/30666052/225537396-8cd11a9d-6d25-4e4e-92af-059bcd49e266.png">

**Suspected Cause**
[_DeleteBlock_ added in version 2.13.16](https://github.com/spicywebau/craft-neo/blob/main/CHANGELOG.md#added-13)

### Steps to reproduce

1. Add an entry with a _Neo_ field in it.
2. Try to delete the saved entry.

### Expected behaviour

The entry should delete properly without any failed job.

### Neo version

2.13.16

### Craft CMS version

3.8.2

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2023-03-21 02:53
If possible, could you please send in your composer.json/lock and database backup to plugins@spicyweb.com.au, and we'll have a look.

**Comment by ttempleton** [comment] 2023-04-05 09:09
Closing this issue as not reproducible, but if the issue persists, please let us know and we'll reopen.

**Comment by ttempleton** [comment] 2023-04-14 05:42
Thanks for sending the files @anita-chouhan. It turned out to be a conflict with some code that the Cache Flag plugin is running on element delete:

```
2023-04-14 12:50:58 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [334] Deleting old Neo blocks (attempt: 1, pid: 2328) - Error (time: 0.007s): Invalid owner ID: 35277
2023-04-14 12:50:58 [-][1][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 35277 in /var/www/html/vendor/spicyweb/craft-neo/src/elements/Block.php:347
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(414): benf\neo\elements\Block->getOwner()
#1 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(452): craft\helpers\ElementHelper::rootElement(Object(benf\neo\elements\Block))
#2 /var/www/html/vendor/mmikkel/cache-flag/src/CacheFlag.php(226): craft\helpers\ElementHelper::isDraftOrRevision(Object(benf\neo\elements\Block))
#3 /var/www/html/vendor/mmikkel/cache-flag/src/CacheFlag.php(180): mmikkel\cacheflag\CacheFlag->_maybeInvalidateFlaggedCachesByElement(Object(benf\neo\elements\Block))
#4 [internal function]: mmikkel\cacheflag\CacheFlag->mmikkel\cacheflag\{closure}(Object(craft\events\DeleteElementEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\DeleteElementEvent))
#6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1699): yii\base\Component->trigger('beforeDeleteEle...', Object(craft\events\DeleteElementEvent))
#8 /var/www/html/vendor/spicyweb/craft-neo/src/jobs/DeleteBlock.php(49): craft\services\Elements->deleteElement(Object(benf\neo\elements\Block), false)
#9 /var/www/html/vendor/yiisoft/yii2-queue/src/Queue.php(246): benf\neo\jobs\DeleteBlock->execute(Object(craft\queue\Queue))
#10 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('334', 'O:25:"benf\\neo\\...', '300', 1)
#11 /var/www/html/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('334', 'O:25:"benf\\neo\\...', '300', 1)
#12 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#13 /var/www/html/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#14 /var/www/html/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#15 /var/www/html/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#16 [internal function]: craft\controllers\QueueController->actionRun()
#17 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('queue/run', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction('queue/run', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /var/www/html/web/index.php(26): yii\base\Application->run()
#25 {main}
```

I'm not really familiar with Cache Flag, unfortunately, but disabling it allowed the jobs to complete, so I'm assuming that Cache Flag will need to catch the case where the Neo (and for that matter Matrix and Super Table) blocks it's handling don't have a valid owner any more, and handle it accordingly.

**Closed by ttempleton** 2023-04-14 05:42 UTC
Labels: not reproducible

**Comment by mmikkel** [comment] 2023-04-24 12:13
The problem here is that unlike Matrix or SuperTable blocks, Neo blocks are deleted asynchronously in a queue job. This means that Neo blocks being deleted will have an `ownerId` attribute referencing an element that no longer exists (since it has been deleted prior), which makes Neo throw [this exception](https://github.com/spicywebau/craft-neo/blob/4f2aea4998e8bbd47f9bf573d5b021dfcecb13e9/src/elements/Block.php#L397) if anything tries to call the these blocks' `getOwner()` method (for example, in an `EVENT_BEFORE_DELETE_ELEMENT` event handler).

In my opinion, Neo should mitigate this issue by making sure that deleted blocks' `getOwner()` method returns a null value.
