### ISSUE TITLE
Nested Matrix fields not resolved when queried with a GraphQL Fragment

### ISSUE THREAD

**Issue by r0skar** [spicywebau/craft-neo#349] opened 2020-05-13 07:16 UTC
#### Description
When using Fragments to query blocks, nested Matrix fields are not resolved:

```gql
query PageData {
  entry(slug: "index") {
    ... on pages_pages_Entry {
      # Neo field
      neoTest {
        ...MediaTest
      }
    }
  }
}

fragment MediaTest on neoTest_mediatest_BlockType {
  # Matrix field
  baseMedia {
    __typename
  }
}
```

returns

```json
{
  "data": {
    "entry": {
      "neoTest": [
        {
          "baseMedia": []
        }
      ]
    }
  }
}
```

Once we inline the fragment like so:

```gql
query PageData {
  entry(slug: "index") {
    ... on pages_pages_Entry {
      # Neo field
      neoTest {
        ... on neoTest_mediatest_BlockType {
          # Matrix field
          baseMedia {
            __typename
          }
        }
      }
    }
  }
}
```
all fields are resolved:

```json
{
  "data": {
    "entry": {
      "neoTest": [
        {
          "baseMedia": [
            {
              "__typename": "baseMedia_image_BlockType"
            }
          ]
        }
      ]
    }
  }
}
```

This is an issue because we have numerous blocks and dont want to inline them all into a huge query (also the apollo:codegen utility will output much nicer types when using Fragments).

#### Other information
- Neo version: 2.7.10
- Craft version: 3.4.18

**Comment by pvldigital** [comment] 2020-05-14 04:18
Hi @r0skar,

it seems like this works:

```
query PageData {
  entry(slug: "index") {
    ... on pages_pages_Entry {
      # Neo field
      neoTest {
        ...neoTest_mediatest_BlockType {
            ...MediaTest
        }
      }
    }
  }
}

fragment MediaTest on neoTest_mediatest_BlockType {
  # Matrix field
  baseMedia {
    __typename
  }
}
```

which is strange.. I'll have a look into the issue.

**Comment by pvldigital** [comment] 2020-05-14 06:35
another thing I noticed was fragmenting works with neo block types but not matrix block types. still looking into the issue.

**Comment by r0skar** [comment] 2020-05-29 11:49
Hi! I was just wondering whether there is any progress on this issue? We are in the middle of creating multiple client projects with Craft+Neo and would really love to refactor our codebase to use Fragments once this bug is resolved.

**Comment by ttempleton** [comment] 2020-05-29 12:40
Hi @r0skar,

I recently tested with Craft's 3.5 beta branch after seeing craftcms/cms#5998, and saw that a Matrix->Super Table fragment query that wasn't working with 3.4 was working with the 3.5 code.  However, Neo->Matrix (and Neo->Super Table, for that matter) wasn't working, so at this stage I'm not sure whether it's something that would need to be fixed on Craft's or Neo's end.

What I do know, at this stage, is that it's failing to eager-load the nested field with a fragment query because it's looking for the field in the wrong place.  I noticed that Craft was looking for `neoField:block1.matrixField` with the inline query, but was looking for `neoField.matrixField` with the fragment query.  I haven't yet determined why that's happening, but I plan to look further into it in the next week and hope to have results by then.

**Comment by ttempleton** [comment] 2020-07-03 13:27
Sorry for the late response to this.  I've been testing tonight after seeing craftcms/cms#6294 and its resolution, and I can confirm that the fix for that issue resolves this issue too.  I'm not sure when the next Craft CMS release will be, exactly, but it seems certain that you will be able to use fragments to query Matrix fields nested within Neo fields with that release.

**Closed by ttempleton** 2020-07-03 13:27 UTC
Labels: bug
