### ISSUE TITLE
Failed jobs in queue manager: "Saving the neo structure for duplicated elements"

### ISSUE THREAD

**Issue by mach1media** [spicywebau/craft-neo#330] opened 2020-04-03 18:48 UTC
#### Description
Failed jobs in queue manager: "Saving the neo structure for duplicated elements." 

#### Steps to reproduce
1. I'm guessing my client may have duplicated a NEO block, but not sure. A bunch of these failed jobs started showing up in the Queue Manager.
2. Go to Utilities > Queue Manager in Craft control panel to see failed jobs.

#### Other information
- Neo version: 2.7.3
- Craft version: 3.4.12
- Is eager-loading used? Yes, eager loading is used in templates, but probably irrelevant for this issue.

**Comment by pvldigital** [comment] 2020-04-03 20:08
Hi @mach1media,

What was the error within the failed job?

**Comment by mach1media** [comment] 2020-04-03 20:38
Thanks for taking a look at this. When I click one of the failed jobs it doesn’t show anything on the detail page, but does show a Craft flash message saying "Error at offset 56893 of 649158 bytes" for each failed job. Of course the offsets are bytes are different for each failed job. Sorry that doesn’t provide much info.

Roger Glenn
Mach 1 Media
roger@mach1media.com
www.mach1media.com
512-922-7384 iPhone

**Comment by pvldigital** [comment] 2020-04-06 00:15
@mach1media can you send your queue.log file to plugins@spicyweb.com.au? i've been trying to replicate but was unsuccessful

**Comment by TimvanDijkhuizen** [comment] 2020-04-10 09:32
@pvldigital I'm also having some major issue's with a site I'm working on. We've got a bunch of nesting and the jobs that NEO is trying to push cause the SQL server to give up: MySQL server has gone away.

The commit above should fix this too. I hope it will be released soon as our client is unable to save some entries. Thanks in advance!

**Comment by nickroberts** [comment] 2020-04-15 00:01
I am getting this same error, as well. Not sure what the issue is. I even killed the db, then started over from the project config. It doesn't seem to be causing any issues with any of the entries, so I have no idea what is going on.

**Comment by pvldigital** [comment] 2020-04-15 01:29
@nickroberts @TimvanDijkhuizen can you answer the points below:

Neo version:
Craft version: 
Is multisite:
PHP version:
Mysql or postgresql: 
Any errors within the failed job:

If you can send your composer.json and lock to plugins@spicyweb.com.au

**Comment by engram-design** [comment] 2020-04-15 02:07
Getting the same error, pretty persistently with a whole other bunch of Neo issues at the moment. Blocks are disappearing as well.

Error message is `Creating default object from empty value`, I'll try to get some more detail in a second.

**Comment by nickroberts** [comment] 2020-04-15 03:29
Pretty much the same thing here. I'm running a headless multi-site install...

## Saving the neo structure for duplicated elements
| | |
| --- | --- |
| ID | 253 |
| Status | Failed |
| Error | Creating default object from empty value |
| Progress | 30% |
| Time to reserve | 300 seconds |
| Priority  | 1024 |
| Pushed at | Apr 14, 2020, 11:20:27 PM |
| Updated at | Apr 14, 2020, 11:20:28 PM |
| Failed at | Apr 14, 2020, 11:20:28 PM |

### Job Data
```
{
    "field": "1",
    "owner": {
        "id": 26,
        "siteId": "4"
    },
    "blocks": [
        {
            "id": 27,
            "sortOrder": 1,
            "lft": "2",
            "rgt": "3",
            "level": "1"
        }
    ],
    "siteId": null,
    "description": null
}
```

**Comment by pvldigital** [comment] 2020-04-15 05:28
@engram-design @nickroberts  thanks for the info. The only issue I'm facing is being unable to replicate it all this time which is baffling to me.

@engram-design interesting that `getBlockById ` needed the `siteId`, I guess multisite requires it so it can narrow down the block.

Can you both also send me your queue logs as well? (to plugins@spicyweb.com.au or attach it with a comment).

**Comment by engram-design** [comment] 2020-04-15 05:58
@pvldigital Not sure if you're testing on a multi-site? I can potentially provide some access to the database. We're facing a couple of other issues with Neo, in that saving drafts in one site completely wipes blocks in all other sites - which is a nightmare for our client.

Sending the queue log to you. Feel free to get in touch on the Craft Discord (handle `crawf`)

**Comment by pvldigital** [comment] 2020-04-15 06:03
@engram-design yep i'm testing with both multisite and non multisite and still wasn't able to replicate the issue. For now I'll make a release that doesn't use job and immediately creates the neo structure. Will look into the draft issue as well.

**Comment by pvldigital** [comment] 2020-04-15 06:22
@engram-design re draft issue: the issue occurs when publishing a draft and not when it auto saves correct?

**Comment by engram-design** [comment] 2020-04-15 07:58
@pvldigital Correct although @javangriff can shed some more details on this. After a bit of testing it seems that the previous issue of blocks losing their nesting has been fixed.

However, when publishing changes from a draft the content of the field within other sites is deleted/overwritten. This is pretty noticeable because using Live Preview does this, as it creates a draft, and the client will then publish these changes.

Does that make sense? Happy if this needs to be another issue.

**Comment by TimvanDijkhuizen** [comment] 2020-04-15 08:39
> @nickroberts @TimvanDijkhuizen can you answer the points below:
> 
> Neo version:
> Craft version:
> Is multisite:
> PHP version:
> Mysql or postgresql:
> Any errors within the failed job:
> 
> If you can send your composer.json and lock to [plugins@spicyweb.com.au](mailto:plugins@spicyweb.com.au)

As I expected my error has already been fixed by version 2.7.6

**Comment by nickroberts** [comment] 2020-04-15 12:14
I haven't seen the disappearing blocks issue, but I haven't really got into dealing with other sites, yet, as I have just been testing on a single site.

As far as versions of things, you can see what versions of plugins I have running in https://github.com/spicywebau/craft-neo/issues/330#issuecomment-613795125.

Here are my composer.json and composer.lock files (in a zip).

[composer-files.zip](https://github.com/spicywebau/craft-neo/files/4481104/composer-files.zip)

**Comment by pvldigital** [comment] 2020-04-16 00:17
@nickroberts thanks. is this occurring with testing it locally and on the live site?

I've made further changes in my latest commit. If possible can you test it out? @engram-design @nickroberts. 
I'm currently testing it myself with single and multi site and will release the changes soon once that's completed.

**Comment by javangriff** [comment] 2020-04-16 02:15
@pvldigital After doing some testing with your latest changes, it looks like the issue has been fixed. After publishing changes from a draft, the contents of the other sites within a multisite setup are unaffected. Thanks for the prompt work on this one and thanks @engram-design for the input.

**Comment by pvldigital** [comment] 2020-04-16 02:27
@javangriff good to know it's working for you. I will release the new version in a bit after some further testing.

**Comment by nickroberts** [comment] 2020-04-16 03:08
This was happening both locally and in a published dev environment.

Glad to hear testing is going well! I haven't had time to go through and test myself, but I hope to in the next day or so, possibly with the latest release (if you make one before I can get to it).

Thanks!

**Comment by pvldigital** [comment] 2020-04-16 03:29
A new version has been released, 2.7.7, which includes changes for this issue.

@nickroberts when you have time test out the new version and see if it resolves it on your end.

**Comment by nickroberts** [comment] 2020-04-16 04:59
I just pulled down the latest release, and it looks like we are good to go. Thanks!

**Comment by pvldigital** [comment] 2020-04-16 08:40
@nickroberts awesome good to know it resolved the issue on your end.

@mach1media has the latest update resolved this issue for you?

**Comment by mach1media** [comment] 2020-04-16 14:23
Yes Peter! The latest release fixed the “Saving the neo structure for duplicated elements” I originally reported. Thank you! 🙏🏻

**Comment by pvldigital** [comment] 2020-04-16 18:50
@mach1media awesome.

**Closed by pvldigital** 2020-04-16 18:50 UTC
