### ISSUE TITLE
Issue with Asset Fields Not Showing in Neo Plugin

### ISSUE THREAD

**Issue by pointblankdevs** [spicywebau/craft-neo#911] opened 2024-07-17 08:17 UTC
### Bug Description

Issue with Asset Fields Not Showing in Neo Plugin

I am using the paid version of the NEO plugin and encountering an issue in Craft CMS. The fields for uploading images and videos are not appearing in the entry editor. I have attached a screenshot showing the problem—specifically, the absence of options to upload images and videos.

![image](https://github.com/user-attachments/assets/5e6e2e96-6894-413a-b758-31bf8b49656b)

### Steps to reproduce

1.
2.
3.

### Neo version

3.8.6

### Craft CMS version

4.10.0

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2024-07-17 11:56
Your Neo version is quite out of date, so I'm going to close this issue.

If you upgrade Neo to the latest version for Craft 4 (currently 4.2.8) and it still occurs, I will recommend that you set up a test entry that only has a Neo field, with block types that only have asset fields, just to rule out the possibility of a bug with some other package causing issues with Neo or asset fields in general.

If it still happens with that test, please let me know, and edit your issue to list detailed steps to reproduce (e.g. the steps you followed setting up that test), and I'll reopen the issue.

**Closed as not planned by ttempleton** 2024-07-17 11:56 UTC
Labels: bug report, bug report status: external cause

**Comment by pointblankdevs** [comment] 2024-07-17 13:07
Hello I have updated the NEO plugin with the latest version of 4.8.2

The issue is still there. I have created a new test field and added a image option. But it is not showing option to add image. Please check

**Comment by ttempleton** [comment] 2024-07-18 05:35
It looks like you haven't set up a test entry that only has a Neo field on its field layout, with block types that only have asset fields. You will need to create a new section and entry type to do that. It is important that no other fields exist on the field layout for that test (including Neo fields with other block types) so we can rule out the possibility of a bug with some other package causing issues with Neo or asset fields in general.

I will also recommend disabling all other plugins while testing that.

**Comment by tommysvr** [comment] 2024-07-18 05:47
Solved in Craft CMS support.

It was due to an update past 4.7 that changed how temporary assets worked. Changing 'Temp Uploads Location' to 'In the local temp folder' from Settings > Assets > Settings resolved the issue.

**Comment by ttempleton** [comment] 2024-07-18 06:06
Thanks for that update @tommysvr.
