### ISSUE TITLE
Ambiguous column: 7 ERROR: column reference "structureId" is ambiguous

### ISSUE THREAD

**Issue by dande-sun** [spicywebau/craft-neo#838] opened 2024-01-31 02:15 UTC
### Bug Description

![WeCom Screenshot_20240131095819](https://github.com/spicywebau/craft-neo/assets/93630861/3d0ce8e3-a2f1-46b1-8939-e4e18b4ace2a)

### Steps to reproduce

Unknown steps, this is a console error, Administrator 1 can open this page, but administrator 2 will happen this error.

### Expected behaviour

Is this a NEO BUG? how to get it working before fixing this BUG.

### Neo version

4.0.2

### Craft CMS version

4.5.15

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2024-01-31 03:10
Likely duplicate of #834 which is fixed in Neo 4.0.3. Please let me know if the update does not resolve the error for you, though.

**Closed by ttempleton** 2024-01-31 03:10 UTC
Labels: bug
