### ISSUE TITLE
New Content will be dropped after saving

### ISSUE THREAD

**Issue by sfsmfc** [spicywebau/craft-neo#906] opened 2024-07-02 08:13 UTC
### Bug Description

Since bugfix https://github.com/spicywebau/craft-neo/commit/f5fd956ffc29245c7d8d422ef257424f04aff932, there is a problem, if you paste neo fields from a not stored content. Copy & Paste from already saved content works fine.

### Steps to reproduce

1. Create new content with a neo field.
2. Copy this content and paste them. 
3. The content will be shown in backend.
4. If you save your entry, the second, pasted content doesn't exists anymore after saving.

### Expected behaviour

The content exists after saving.

### Neo version

> = 4.2.1

### Craft CMS version

> 4.9.x

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2024-07-02 08:57
I'm unable to reproduce this, so I'm guessing this has been fixed since 4.2.1. Please upgrade to the latest Neo 4 release (~~4.2.5~~ now 4.2.6) and let me know how that goes.

**Comment by sfsmfc** [comment] 2024-07-02 10:06
Hey @ttempleton, I have test it with all 4.2.x versions and the result is always the same. The second element will not be saved. 

If I use version 4.1.x, all elements are saved.

I have test it with different neo "subelements" and I can reproduce it with all.

**Comment by sfsmfc** [comment] 2024-07-02 10:12
I have upload a video with the problem. I hope this can help you to understand my problem.

https://github.com/spicywebau/craft-neo/assets/5294925/77a8629d-8913-486f-bf88-f729c627a7f3

**Comment by ttempleton** [comment] 2024-07-03 11:46
Thanks for posting that video - I was able to reproduce it, and it's fixed now in 4.2.7.

**Closed as completed by ttempleton** 2024-07-03 11:46 UTC
Labels: bug report, bug report status: fixed
