### ISSUE TITLE
Neo fields disappear on certain entries after adding a new field.

### ISSUE THREAD

**Issue by boraunal** [spicywebau/craft-neo#61] opened 2016-11-22 13:07 UTC
When I add a new neoblock to an entry, previous blocks disappear. This happens on some records.

Resolution is to revert back to a previous version to the entry and save as a new entry. After saving as a new entry problem does not repeat.

We are on Craft version: 2.6.2949

**Comment by benjamminf** [comment] 2016-11-28 04:42
- What version of Neo are you running?
- Have you since added localisation/an additional locale to the site since adding the Neo blocks?

**Comment by boraunal** [comment] 2016-11-28 11:39
Hi Benjamminf,

Our version is Neo 1.3.5
Yes Neo fields are localised.
No, localisation added at the beginning.

**Comment by ttempleton** [comment] 2019-03-15 11:15
I believe, based on the description of the problem being resolved by saving as a new entry, that the cause of the disappearing blocks in this case was probably the same as #128 where more than one block structure existed for the affected field/entry/locale combination.  [Neo 1.5.1](https://github.com/spicywebau/craft-neo/releases/tag/1.5.1) includes block structure cleanup in case an extra one is somehow created, so we'll close this issue now, but @boraunal if the affected site still runs Craft 2 and this still happens with Neo 1.5.1, please let us know!

**Closed by ttempleton** 2019-03-15 11:15 UTC
