### ISSUE TITLE
Question - blocks duplicated on entry in production

### ISSUE THREAD

**Issue by mikeatmostlys** [spicywebau/craft-neo#611] opened 2022-06-28 12:07 UTC
#### Description
On a couple recent projects, I found Neo blocks were duplicated on an entry in production. Regretfully, I have not been able to replicate the issue, and I understand if nothing can be done to address it `¯\_(ツ)_/¯`

I'm reporting it here in case anyone else has come across the same issue before, or has insight to share.

#### Versions
- Neo version: 2.13.5
- Craft version: 3.7.38
- Not multi-site

The duplicate blocks were found in production shortly after deploying a new commit. (Duplicate blocks did not occur in local dev). The commit before the duplicates were found included project config changes to a Neo block field.

The deploy process to production is:
- `git push` to Fortrabbit app
- which runs `composer install`
- than `craft migrate/all`
- and `craft project-config/apply`

Admin changes are not allowed in production.
 
I noticed that duplicate blocks were mentioned in the [change log here](https://github.com/spicywebau/craft-neo/blob/master/CHANGELOG.md#2124---2022-02-01) but our projects were not multi-site.

Happy to provide further info if it's helpful. Thanks for the plugin!

**Comment by ttempleton** [comment] 2022-06-29 06:57
If you have a database backup from when that happened (or if anyone else is having the issue) then I'd be interested to know if the duplicated blocks have the same ID or not - if they have the same ID, then it might be a case of a duplicated block structure.

**Comment by mikeatmostlys** [comment] 2022-06-30 12:59
From a DB backup, I was able to get some info on the duplicate block rows. They do not have the same id.

| id    | ownerId | ownerSiteId | fieldId | typeId | sortOrder | deletedWithOwner | dateCreated         | dateUpdated         | uid                                  |
|-------|---------|-------------|---------|--------|-----------|------------------|---------------------|---------------------|--------------------------------------|
|  2873 |      17 |             |      73 |     17 |         1 |                0 | 2022-02-14 23:21:21 | 2022-02-14 23:21:21 | 5b09129d-90fd-4a0b-a9c5-992e0c0bd5a8 |
| 29996 |      17 | NULL        |      73 |     17 |         2 | NULL             | 2022-05-03 16:43:24 |  2022-05-12 0:36:12 | f64db611-c626-45f2-8484-09facf47ff4b |
|       |         |             |         |        |           |                  |                     |                     |                                      |

**Comment by Kethatril** [comment] 2022-07-01 02:27
I just had the exact same thing happen and it is also not a multi-site. For a single entry all the neo blocks were duplicated. The duplicated blocks had new ids as well. I think it happened after a code change however I'm in the process of verifying exactly when it happened.

**Comment by ttempleton** [comment] 2022-07-01 04:04
The DB rows are interesting since the first one has `deletedWithOwner` set to 0 (meaning that the block _has_ been deleted, just not as a result of the owner element being deleted) so it shouldn't be showing up on the entry. Does the row in the `elements` table with that ID have a `dateDeleted` value?

Other than that, it turns out that there was an issue opened with Craft about duplicated Neo blocks a couple of months ago (https://github.com/craftcms/cms/issues/11250), so if anyone with this issue can reliably reproduce this, could you please also test with a Matrix field, and comment here and on the Craft issue with your results.

**Comment by mikeatmostlys** [comment] 2022-07-01 13:25
Interesting, there is no value in dateDeleted for the first entry in the elements table.
| id    | canonicalId | draftId | revisionId | fieldLayoutId | type                    | enabled | archived | dateCreated         | dateUpdated         | dateLastMerged | dateDeleted | uid                                  |
|-------|-------------|---------|------------|---------------|-------------------------|---------|----------|---------------------|---------------------|----------------|-------------|--------------------------------------|
|  2873 |             |         |            |            53 | benf\neo\elements\Block |       1 |        0 | 2022-02-14 23:21:21 | 2022-05-12 18:00:59 |                |             | d6e4f7b9-ac4b-4f76-87e7-db9359cb019e |
| 29996 | NULL        | NULL    | NULL       |            53 | benf\neo\elements\Block |       1 |        0 | 2022-05-03 16:43:24 | 2022-05-12 18:00:59 | NULL           | NULL        | 223b57d6-9fd5-479f-9b4e-fc5cc09252aa |
|       |             |         |            |               |                         |         |          |                     |                     |                |             |                                      |

**Comment by ttempleton** [comment] 2022-07-17 04:25
Given the recent posting of https://github.com/craftcms/cms/issues/11609 concerning duplication of Matrix blocks, I'm going to assume there's a common cause in Craft itself and close this issue, but happy to reopen if the Neo block duplication turns out to be unrelated.

**Closed by ttempleton** 2022-07-17 04:25 UTC
Labels: help wanted

**Comment by mikeatmostlys** [comment] 2022-07-18 20:38
Thank you! I've subscribed to the issue you mentioned.
