### ISSUE TITLE
Losing content when applying drafts or previous versions

### ISSUE THREAD

**Issue by jegra** [spicywebau/craft-neo#481] opened 2021-07-19 21:15 UTC
#### Description
When new Neo blocks are added and then saved, the newly added content disappears (the block reappears in the edit screen empty).  When trying to revert to earlier versions of the page, blocks are all empty when the page reverts/refreshes.  

**UPDATE:** after another project config update, we're seeing new blocks saving correctly, but drafts do not appear to be working.  After saving a draft, and then coming back and applying it, the draft modifications are lost.  Also, when trying to revert to a previous version, applying the version doesn't fully 'take'.  Clicking the 'Revert entry to this revision' button refreshes the page to the same state it was originally in, with the 'Revert' button still active.

#### Steps to reproduce
1. Add a new Neo block to a page entry and populate it with content
2. Click 'Create a draft'
3. Click 'Save draft'
4. Return to edit page
5. Select previously saved draft (changes appear correctly placed)
6. Click 'Apply Draft'
7. Page refreshes - newly added block disappears

**UPDATE 2 - REVISED:** content save issue appears to be addressed by Craft 3.7.4.  Draft/revisions issue still exists.

#### Other information
- Neo version: 2.11.1
- Craft version: 3.7.3.2
- (if multi-site) What is the affected Neo field's propagation method: Save blocks to all sites the owner element is saved in
- Is eager-loading used? No

Commented on similar issue in #480, but wanted to add more info/context here...

**Comment by ttempleton** [comment] 2021-07-20 02:11
Regarding the draft content loss: could you please test that with a Matrix field and confirm whether that works as expected?

I'm assuming the revision content loss is related to that reported in craftcms/cms#9601 and #480.

**Comment by jegra** [comment] 2021-07-20 02:20
hi @ttempleton - confirming that matrix fields work as expected.  behavior is only seen in neo fields.

**Comment by ttempleton** [comment] 2021-07-20 05:05
Thanks for confirming that @jegra.  If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au along with details of an entry where this is happening, and we'll have a look at it.

**Comment by jegra** [comment] 2021-07-20 10:59
thanks @ttempleton - files sent (please let me know if you didn't receive...)

**Comment by webkp** [comment] 2021-07-21 08:56
Thank you for already creating this issue @jegra, I encountered the very same problem yesterday. Fortunately I was able to copy the content from the draft-view (step 5 from @jegra's reproduction description), otherwise I would have lost the content.

**Comment by ttempleton** [comment] 2021-07-22 12:55
Thanks for sending those files @jegra.  It looks like the block structure management when merging draft/live content together will need to be rewritten to fix this.  I'll work on it and let you know when I have an update regarding a new release.

**Comment by jegra** [comment] 2021-07-22 13:00
ok, thanks for the update @ttempleton - much appreciated.

**Comment by ttempleton** [comment] 2021-07-27 03:43
Those draft/revision issues should now be fixed in Neo 2.11.3.

**Closed by ttempleton** 2021-07-27 03:43 UTC
Labels: bug

**Comment by jegra** [comment] 2021-07-28 17:01
hi @ttempleton - have tested for both the draft and the revision issues in the 2.11.3 update, and both look good.  thanks much!
