### ISSUE TITLE
[craft 4]Dragging and moving neo blocks no longer working 

### ISSUE THREAD

**Issue by yonaeldawit** [spicywebau/craft-neo#956] opened 2024-10-30 17:25 UTC
### Bug Description

When trying to grab a block and drag it up or down, it doesnt work. i can go to the gear icon and move blocks up or down but not using the moving one. It only doesnt work for the child blocks. The parent blocks move around as expected but not the child blocks. 

![Screenshot 2024-10-30 at 1 21 21 PM](https://github.com/user-attachments/assets/a907f42f-daca-4307-b392-341773d81226)
Sc of neo blocks with their children field layout

![Screenshot 2024-10-30 at 1 21 44 PM](https://github.com/user-attachments/assets/76e819bf-841b-4830-ac16-1f7802c38811)
SC of how its being used. the rearraging icon doesnt seem to drag down nor up

### Steps to reproduce

1. Create neo with 2-3 levels
2. Try to drag lvl 2 blocks with the rearranging icon

### Expected behaviour

Child blocks should be draggable and reorderable, just like parent blocks.

### Neo version

4.12.13

### Craft CMS version

4.12.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2024-10-30 22:44
I'm unable to reproduce this, but both your Craft and Neo versions are a bit out of date, so try upgrading those, and let me know if the issue persists.

**Comment by ttempleton** [comment] 2024-11-22 04:44
Closing this issue, but let us know if the issue persists and we'll reopen.

**Closed as not planned by ttempleton** 2024-11-22 04:44 UTC
Labels: bug report, bug report status: not reproducible
