### ISSUE TITLE
Nested blocks jumping out of parent block

### ISSUE THREAD

**Issue by rstix** [spicywebau/craft-neo#510] opened 2021-10-29 06:24 UTC
#### Description
We have Neo field with nested blocks. If some of them are added to the entry and saved the nested blocks are jumping out of the parent block and then the entry is not rendering:
<img width="954" alt="Screenshot 2021-10-28 at 08 36 47" src="https://user-images.githubusercontent.com/23715446/139385449-716ebfce-e786-448b-ae66-c635f307961a.png">
As seen above there is Logo Slider and below is Logo Slider Element which should be inside the Logo Slider. But it get out after saving the entry.

Here is how it looked before saving: 
![image](https://user-images.githubusercontent.com/23715446/139385730-8e210f89-12ca-4b8f-80c3-867930e1c278.png)

#### Steps to reproduce
I was able to reproduce it only in some entries. I can give access to our CMS so you can see that it is happening.

#### Other information
- Neo version: 2.11.13
- Craft version:  3.7.17
- Is eager-loading used? no

**Comment by satcreative** [comment] 2021-11-02 12:34
I have also had instances where child blocks are been moved outside the parent block. I then have to drag them back in and resave.

This happens randomly and am unable to say what triggers this. It's not until I see the missing content on the frontend that I'm aware of the issue within a particular entry.

I has occurred a few times now, most recently today (I noticed it today).

**Current versions:**
Craft Pro: 3.7.16
Neo: 2.11.14

**Comment by ttempleton** [comment] 2021-11-03 01:43
@rstix are you able to reliably reproduce this on one of the entries where it's happened? If so, could you please send a database backup and your composer.json/lock to plugins@spicyweb.com.au and we'll have a look at it. I'm guessing that something is going wrong with the block structure merging in some cases when merging draft content into a live entry, but I'm unable to reproduce it locally so far.

**Comment by ttempleton** [comment] 2021-11-08 05:51
I've just released Neo 2.11.16 which fixes a different case of incorrect merging of blocks into another block structure. The fix for that should also fix this issue, so I'm going to close it. If the issue persists, let me know and I'll reopen it (and, if possible, any information about how to reliably reproduce it would be greatly appreciated).

**Comment by rstix** [comment] 2021-12-15 00:07
@ttempleton I have sent the composer files and the database to the plugins adress.

**Comment by ttempleton** [comment] 2021-12-15 00:36
Thanks @rstix. Will look into it today.

**Comment by ttempleton** [comment] 2021-12-15 12:53
Just wanted to give an update on this: it turns out that in some cases, Neo is incorrectly reassigning the blocks' sort order instead of using the actual order of the blocks, and that's causing the blocks to move out of place. I have a possible fix in place which seems to be working, will just need to do some more testing to make sure it doesn't have any unintended effects before releasing it.

**Comment by ttempleton** [comment] 2021-12-16 09:58
Looks like everything is fine with the fix, so it's been included in the just-released Neo 2.12.1. Sorry again for the mixup.

**Closed by ttempleton** 2021-12-16 09:58 UTC
Labels: bug

**Comment by john-henry** [comment] 2022-02-23 22:25
I can reproduce this in Neo 2.12.5 & Craft CMS 3.7.33. In our case the client managed to drag the nested block out of its position into the same level as its parent block causing all sorts or issues

**Comment by john-henry** [comment] 2022-02-24 10:28
Will do. Let me get a vanilla install setup and create an issue if I can reproduce. Thanks
