### ISSUE TITLE
Re-order Neo block not working on multisite  after updating from 3.1.8

### ISSUE THREAD

**Issue by bzin** [spicywebau/craft-neo#630] opened 2022-07-28 08:17 UTC
#### Description

After updating Neo from 3.1.8 to 3.2.2, re-ordering and disable blocks stop working, it also made blocks completely disappear on another Site where they would be propagated but translated. I had to revert back to 3.1.8 to have everything working again.

#### Other information
- Neo version: 3.2.2
- Craft version: Craft Pro 4.2.0.2

**Comment by ttempleton** [comment] 2022-07-28 08:30
I can see some issues with block reordering having unintended effects in some cases so will look into that. Regarding disabling blocks not working, steps to reproduce would be helpful.

**Comment by maxstrebel** [comment] 2022-07-28 08:37
I also get several reports from one of my clients (is on NEO 3.2.1). They report blocks "that the elements have started to jump, even after moving back to their actual spots and it keeps on happening".

**Comment by bzin** [comment] 2022-07-28 09:09
Hi @ttempleton ,

The disable function I am referring is when I have some multiple Neo blocks and I disable these via the top right dropdown in the block item:
<img width="366" alt="CleanShot 2022-07-28 at 11 07 01@2x" src="https://user-images.githubusercontent.com/382735/181467627-127cc6e2-38ab-4839-b06e-8fa31371b4aa.png">
Basically when I disable and save, these will do nothing and it would still be enabled.

**Comment by jesuismaxime** [comment] 2022-07-28 14:18
Also got an unexpected behaviour with ordering with Neo v3.2.2 (Unable to re-order blocks on save, they keep the same order; try with both autoSaveDraft activate and deactivate).

**Comment by jesuismaxime** [comment] 2022-07-28 14:24
Well that was quick 😆. Do you have a release (date/time) in mind for this fix?

**Comment by ttempleton** [comment] 2022-07-28 14:26
Thanks for the information @bzin, I was able to reproduce it and it should be fixed now.

@jesuismaxime Just released Neo 3.2.3 (please let me know if there are any other issues with reordering blocks!)

**Comment by jesuismaxime** [comment] 2022-07-28 14:39
@ttempleton, tested locally and it works fine now! Thanks a lot!

**Comment by jesuismaxime** [comment] 2022-08-01 19:39
@ttempleton the native issue that imply 'disable stops working' is still there. Since my issue was about the re-ordering, I didnt think to look at the disable part; but it seems to be still there on v3.2.4

**Comment by ttempleton** [comment] 2022-08-02 02:02
Just retested on 3.2.4 and it's still working for me. If you're still having issues with that, could you please open a new issue with as much info as possible regarding steps to reproduce.

**Comment by ttempleton** [comment] 2022-08-02 04:36
I just saw it happening with `autosaveDrafts` set to `false`, no need to open a new issue.

**Closed** 2022-08-02 05:04 UTC
Labels: bug

**Comment by ttempleton** [comment] 2022-08-02 05:05
That should be fixed for non-autosaved elements now, for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.2.4` and running `composer update`.

**Comment by ttempleton** [comment] 2022-08-03 02:12
Just released Neo 3.2.5, including the fix for the block enabled/disabled state being lost when editing non-autosaved elements. If there are still any issues with the enabled/disabled state being lost anywhere, please let me know.

**Comment by bzin** [comment] 2022-08-10 10:24
Thanks a lot @ttempleton,still was not able to test this in the project mentioned above but I am sure it would be working now 😏
