### ISSUE TITLE
Blocks get deleted if disabled

### ISSUE THREAD

**Issue by Sam-Black-0013** [spicywebau/craft-neo#192] opened 2019-02-23 09:18 UTC
#### Description
When I try to disable a block, they get deleted after I save my entry

#### Steps to reproduce
1. Create a block in a global set
2. Save the global set
3. disable that block and save
4. Gone

#### Other information
- Neo version: 2.2.4
- Craft version: 3.1.12
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes

**Comment by ttempleton** [comment] 2019-02-23 11:53
Closing this issue as a duplicate of #190.

**Closed by ttempleton** 2019-02-23 11:53 UTC
Labels: duplicate
