### ISSUE TITLE
Exception "Unable to location message source" when changing propagation method of Neo field

### ISSUE THREAD

**Issue by joshuapease** [spicywebau/craft-neo#815] opened 2023-12-05 18:43 UTC
### Bug Description

I came across the following exception when changing the propagation method of a Neo field. 

"Unable to location message source for category `neo`"

![image](https://github.com/spicywebau/craft-neo/assets/2145998/d535332c-4dbe-4f55-9e80-35c5fb2543d6)

I think it's caused by this attempting to translate the description of this [Queue Job](https://github.com/spicywebau/craft-neo/blob/9faf98cc1e26dd90f2076d9f8bd56998d62377d9/src/console/controllers/FieldsController.php#L142).

I haven't had the time to determine if it's because that string is missing in [translations/en/neo.php](https://github.com/spicywebau/craft-neo/blob/9faf98cc1e26dd90f2076d9f8bd56998d62377d9/src/translations/en/neo.php) or if perhaps the plugin's translation file hasn't been fully loaded when reading the description from the queue job.

Could be something else entirely.

### Steps to reproduce

1. Create a Neo Field & Save
2. After saving the field, modify the propagation method (doesn't seem to matter which you choose as long as it's different than before).
3. The exception should be thrown as soon as the `Applying new propagation method to Neo blocks` job is read from the queue.

### Neo version

3.9.5

### Craft CMS version

4.5.7

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2023-12-07 04:21
I'm unable to reproduce this, but are you able to save entries with Neo fields without any problems, where the entry's section is set to save revisions, and Craft's `runQueueAutomatically` setting is not disabled? [The queue job for saving revision block structures](https://github.com/spicywebau/craft-neo/blob/9faf98cc1e26dd90f2076d9f8bd56998d62377d9/src/jobs/SaveBlockStructures.php) also has a translation set using `Translation::prep()`. It might also be worth trying to change the propagation method of a Matrix field, [which applies the propagation method in much the same way](https://github.com/craftcms/cms/blob/99a8f9a688483d38bdb8cefbf39ad43a5e7b7b82/src/fields/Matrix.php#L1048-L1071) (albeit using the `'app'` category for translations rather than `'neo'`).

Another suggestion is to open the Neo field settings page in your development environment, change the propagation method, then insert `\Craft::dd($this->translations);` into the `getMessageSource()` method of your `vendor/yiisoft/yii2/i18n/I18N.php` file just before the `InvalidConfigException` is thrown, then save the field and see which categories get shown (in particular, whether other plugins' categories aren't appearing).

**Comment by ttempleton** [comment] 2024-01-03 11:05
Closing this issue as not reproducible.

**Closed by ttempleton** 2024-01-03 11:05 UTC
Labels: bug

**Comment by maxfenton** [comment] 2024-02-21 18:51
For what it’s worth, this came up in conversation today and I've had the exact same issue with multi-sites and SuperTable and locally running `craft queue/release all` fixes it for me.
