### ISSUE TITLE
Neo does not show the tab with error after save

### ISSUE THREAD

**Issue by romainpoirier** [spicywebau/craft-neo#299] opened 2020-02-19 14:14 UTC
#### Description

In case of empty required field located in tab on _Save_, there is no highlight of which tab caused the error.

This is very difficult to guess on a page with a lots of Neo blocks with tabs. You need to to click on each tab until you found the empty field to complete.

I sometimes got feedbacks from clients which does not understand why there is an error warning on top of the page after save, and why the page is not saved.

In this example, there is an error:
![neo-field-error-found](https://user-images.githubusercontent.com/4634192/74842162-35871b00-532a-11ea-9a5e-6761ad37f6b2.png)

But you can only see where it is located after click on the tab:
![neo-field-tab-error](https://user-images.githubusercontent.com/4634192/74842171-39b33880-532a-11ea-9f65-7758484aa4f1.png)

Example of field config:
- Sections (Neo Field)
	- Posters (Neo Top Level block)
		- Poster(Neo Child Block)
			-  Link (Matrix Field)

#### Steps to reproduce
1. Setup a Neo field with a required field within a tab
2. Leave this required field empty
3. Save the Entry

#### Other information
- Neo version: 2.6.1
- Craft version: Craft Pro 3.4.6.1
- Is eager-loading used? No

**Comment by pvldigital** [comment] 2020-02-24 23:06
Hi @romainpoirier,

I have replicated the issue and will be working on a fix.

**Comment by pvldigital** [comment] 2020-02-28 01:47
Small update: It looks like the issue is specifically with the matrix field sitting within a neo field. I've made some changes and will push a fix out soon.

**Comment by pvldigital** [comment] 2020-02-28 02:01
release v2.6.2 has a fix for this issue.

**Comment by romainpoirier** [comment] 2020-02-28 09:00
Thank you! I can confirm this is much more clear now.

However, I found a special case that perhaps could still be improved: if the block is not expanded, there's still no highlight of an error (see screenshot below).

![not-expanded](https://user-images.githubusercontent.com/4634192/75525902-fe42f900-5a10-11ea-9d9b-04b062ecabda.png)
![expanded](https://user-images.githubusercontent.com/4634192/75525895-fc793580-5a10-11ea-8f78-ff54d04627a9.png)

**Comment by pvldigital** [comment] 2020-03-01 21:28
Ah I'll add the a highlight on the block name as well.

**Comment by pvldigital** [comment] 2020-03-04 03:59
Changes has been made for this issue in v2.6.3

**Closed by pvldigital** 2020-03-04 03:59 UTC
