### ISSUE TITLE
Job: There was a problem getting the parent element

### ISSUE THREAD

**Issue by leevigraham** [spicywebau/craft-neo#692] opened 2022-12-12 03:04 UTC
#### Description

![Screenshot 2022-12-12 at 2 00 09 pm](https://user-images.githubusercontent.com/25124/206951601-85801e64-3813-4b90-b1b5-2dad04d653a5.png)

While running `./craft up` which changed some propagation methods we're seeing some errors.

#### Steps to reproduce

Cannot reliably reproduce.

#### Other information

- Neo version: 2.13.15
- Craft version: 3.7.53.1

**Comment by ttempleton** [comment] 2022-12-15 09:57
I'm unable to reproduce this error, but if you have a database backup where this has occurred, and retrying the job fails with the same error, could you please send that database backup and the project's composer.json/lock files to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by ttempleton** [comment] 2023-01-19 12:51
I'm going to close this for now, but happy to reopen it if the issue persists.

**Closed** 2023-01-19 12:51 UTC
