### ISSUE TITLE
Getting Undefined Array Key error when saving

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#784] opened 2023-09-10 16:15 UTC
### Bug Description

Hi,

I'm seeing an error when I save entries with a Neo field on a site I'm working on. The error says undefined array key and the name of the array key is a block type that I had created and later removed. The entry still saves all of the new content etc. so I think the error is occurring after the content is saved to the DB, but before it moves to the end of the entry save process.

### Steps to reproduce

1. create a block in type in Neo field setup save it.
2. Go to a page with the neo field and create some content (note, it does not have to include one of your test blocks)
3. Go back to the Neo setup and delete the test block type.
4. Go back to the entry and try to save some new content in the Neo field.

### Expected behaviour

It should save the entry and then either go back to the entries page, or stay in the entry edit field depending on which save button was clicked.

### Neo version

3.8.6

### Craft CMS version

4.5.3

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by brianrivet-tilt** [comment] 2023-09-10 16:17
Actually correction, it does not save the changes to the entry itself. It keeps it as unsaved changes on the entry as a draft.

**Comment by brianrivet-tilt** [comment] 2023-09-10 16:28
Also, the error only seems to happen on entries that were created prior to the block being removed form the Neo field.

**Comment by ttempleton** [comment] 2023-09-10 23:04
Duplicate of #783 which is fixed for the next release.

**Closed** 2023-09-10 23:04 UTC
Labels: bug
