### ISSUE TITLE
Neo blocks unexpectedly scrambled when editing pages

### ISSUE THREAD

**Issue by gateszies** [spicywebau/craft-neo#677] opened 2022-11-23 23:01 UTC
#### Description
We are experiencing problems with Neo blocks unexpectedly moving around when editing pages (might be a duplicate of issue #647). When our authors attempt to create a draft or save edited content in Craft, the structure of the Neo blocks will get scrambled causing the page layout to break. The error typically moves each nested Neo block down into the next parent block. 

Our authors can put the layout back together again, but it continues to break in the same way upon every edit of the page. It also doesn't consistently affect other pages that include Neo blocks and there isn't a clear correlation for why certain pages are affected. 

I've included two screen records of our common problems. The first shows the child blocks being scrambled / pushed down the page when hitting Create a Draft. The second shows the error message that occasionally appears when hitting Create a Draft. We've also experienced the same issue when editing and saving content on the affected pages.
[Screen Record 1](https://user-images.githubusercontent.com/66807975/203659396-31560081-cfb4-429e-85cf-a166bc7975be.mp4)
[Screen Record 2](https://user-images.githubusercontent.com/66807975/203659462-b1463598-6cdd-4b40-b4c6-49487e831baa.mov)

We are currently blocked from making changes on our site and are hoping to get some help resolving the problem. If it helps at all we'd be happy to find a time to meet with you on Zoom and show you the issue or offer any assistance that may help in narrowing it down.

#### Steps to reproduce
1. Go to the affected pages in Craft
2. Edit content in Neo blocks and Save (or simply hit Create a Draft without editing content)
3. Blocks are scrambled or error message appears

#### Other information
- Neo version: 3.3.9
- Craft version: 4.2.5.1
_Note: We did update both Neo & Craft to their latest versions locally while debugging and this did not resolve the issue._
 - No eager loading used

**Comment by ttempleton** [comment] 2022-11-24 01:39
I'll assume duplicate of #647, but I'll close that issue instead for now, as this issue has more information.

If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au, and we'll have a look at it.

**Comment by gateszies** [comment] 2022-11-29 22:05
Just sent an email over with that information @ttempleton. Appreciate the help.

**Closed** 2022-12-02 06:19 UTC

**Comment by ttempleton** [comment] 2022-12-02 06:27
Thanks for sending that @gateszies - both the block scrambling and the error message should be fixed now in Neo 3.5.7.

@maxstrebel please let me know if 3.5.7 resolves the issue for you as well.
