### ISSUE TITLE
hasDescendent() not available within saveEntry event

### ISSUE THREAD

**Issue by cole007** [spicywebau/craft-neo#92] opened 2017-03-15 11:48 UTC
I'm trying to capture an entry on save using the `craft()->on('entries.onBeforeSaveEntry')` and `craft()->on('entries.onSaveEntry')` events. 

I want to try and map the element IDs of the entry before and after save.
For `onBeforeSaveEntry` this is fine - I can loop through the Neo blocks and log their level, etc by targeting the `hasDescendents()` property.

However, for `onSaveEntry` this information is not available with `hasDescendents` returning empty. 

Probably a bit of an edge case but any thoughts why this might be the case?

Cole

**Comment by ttempleton** [comment] 2021-06-10 06:24
Going to close this issue now, given its age and no other reports of this problem.  Sorry it wasn't addressed until now.  For the record, I went back and tested with Neo 1.4.1 / Craft 2.6.2967 which were the latest versions at the time this issue was opened, and couldn't reproduce it.  If I had to guess, though, it could've been caused by some other issues Neo 1.x had with block structures at the time (specifically #128 which involved excess block structures being created, potentially it could've failed to find that it had descendants if it was looking at the wrong block structure).

**Closed by ttempleton** 2021-06-10 06:24 UTC
