### ISSUE TITLE
[Craft 4] Redactor field input disappears within Neo field on save

### ISSUE THREAD

**Issue by Nellyaa** [spicywebau/craft-neo#562] opened 2022-04-22 18:21 UTC
#### Description

The rich text/redactor field disappears when used within a Neo field after hitting save initially. When you press 'add' it will appear and will be editable just fine, but is not accessible afterwards, e.g. after hitting save and the page refreshes.
As using a redactor field as is or within a Craft matrix works just fine, I assume the problem lies with the Neo plugin.
The console logs a lot of errors, see attached screenshots.

This seems to be a backend issue only, as the content of the field is still there and will be rendered as expected in the frontend. 

#### Steps to reproduce
1. Create a Neo field 
2. Add any blocktype
3. Edit the field layout of said blocktype to contain a Redactor field
4. Save
5. Attach neo field to an entry
6. Edit the entry with the neo field and create a block with the rich text field
7. Save the entry and wait for page refresh
8. Observe the redactor field is now missing it's input field

#### Other information
- Neo version: 3.0.0-beta.3
- Craft version: Craft Pro 4.0.0-beta.4
- Redactor version: 3.0.0-beta.2
- (if multi-site) What is the affected Neo field's propagation method: no multisite
- Is eager-loading used? Backend problem only

![Unbenannt-1](https://user-images.githubusercontent.com/38379317/164771515-9934a2b9-337d-4ec4-a64a-33a098d34d9a.jpg)
![Unbenannt-2](https://user-images.githubusercontent.com/38379317/164771521-45c73896-1893-4fb9-b71a-235379bfff2e.jpg)

**Comment by Nellyaa** [comment] 2022-04-22 19:48
Just noticed the very same happens with Icon Picker fields by Verbb as well.

**Comment by internetztube** [comment] 2022-04-25 14:24
Same issue here.

**Comment by ttempleton** [comment] 2022-04-26 05:16
Thanks for reporting this, I was unable to reproduce an error with the Icon Picker field, but the Redactor field error should now be fixed in Neo 3.0.0-beta.4.

**Closed by ttempleton** 2022-04-26 05:16 UTC
Labels: bug

**Comment by Nellyaa** [comment] 2022-04-26 08:03
Works again, icon picker field included. Thanks!
