### ISSUE TITLE
Import full Neo filed config to new installation

### ISSUE THREAD

**Issue by wedot** [spicywebau/craft-neo#198] opened 2019-03-21 05:27 UTC
#### Description
How to import the Neo field setup to a other installation via project.yaml? I'm new in the topic CLI and project.yaml so it may be an easy question to answer. 

#### Steps to reproduce
1. I've moved the project.yaml to the new installation and have imported this. But i only get a empty Neo field.

#### Other information
- Neo version: Neo 2.2.6
- Craft version: Craft CMS 3.1.19
- Is the affected Craft installation multi-site: No
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:

**Comment by boboldehampsink** [comment] 2019-03-21 09:58
I'm seeing this too - looks like a serious bug

**Comment by ttempleton** [comment] 2019-03-22 08:18
The fix for project config syncing in Neo 2.2.6 involved using the `craft\services\ProjectConfig::defer()` method to delay the importation of block types until the associated Neo field has been imported.  That said, if it's deferred for too long, it will eventually give up.  Unfortunately, we're yet to reproduce this issue, but I think, for some reason, that is what's happening here.

Does an attempted re-sync (after making some small change to the original project) work?  Clearly that's not an ideal solution and we'd need to see what we could do to resolve that, but it would at least let us know whether a deferral timeout is happening the first time or there's a more serious issue involved.

The other possibility is if the Neo field is somehow getting a different UID on the target Craft install, which would cause the block type importation to fail.  I think that's unlikely, since that'd be under Craft's control and it seems everything else works.  If the re-sync doesn't work, though, we'd be interested to know if anything has changed with the Neo field's UID.

**Comment by ttempleton** [comment] 2019-03-22 19:37
@wedot, @boboldehampsink, you can probably disregard my previous comment.  The method for ensuring the field exists before the block types has changed in Neo 2.2.7.  Can you please update Neo, re-attempt the importation with a new installation and let us know how it goes?

**Comment by boboldehampsink** [comment] 2019-03-25 14:43
It didn't work for me!

**Comment by boboldehampsink** [comment] 2019-03-26 12:44
Looks ok here now. Only thing I'm finding is that Block Type Groups are created twice, see database screenshot:

<img width="926" alt="Screen Shot 2019-03-26 at 13 44 28" src="https://user-images.githubusercontent.com/378974/54997969-4cfc3d80-4fcd-11e9-8c0f-767458ff6517.png">

**Comment by boboldehampsink** [comment] 2019-03-26 13:15
I fixed that in here: https://github.com/spicywebau/craft-neo/pull/200

**Comment by ttempleton** [comment] 2019-03-27 09:33
Thanks @boboldehampsink!

@wedot -- we'll close this issue now, but if you still have project config issues with Neo 2.2.8, please let us know and we'll reopen the issue.

**Closed by ttempleton** 2019-03-27 09:33 UTC
Labels: bug

**Comment by wedot** [comment] 2019-03-27 20:24
@ttempleton It works great! Thank you for the fix!
