### ISSUE TITLE
Neo blocks unexpectedly scrambled when current version is merged into pre-existing draft

### ISSUE THREAD

**Issue by gateszies** [spicywebau/craft-neo#704] opened 2023-01-24 20:51 UTC
### Bug Description

We are experiencing problems with Neo blocks unexpectedly moving around when the current version of an entry is merged into a pre-existing draft (potential duplicate of our other issues https://github.com/spicywebau/craft-neo/issues/677 https://github.com/spicywebau/craft-neo/issues/694).

When our author makes changes to the current version of an entry, the structure of the Neo blocks on pre-existing drafts will get scrambled causing the page layout to break. This bug typically moves each nested Neo block down into the next parent block.

[Screen Record](https://user-images.githubusercontent.com/66807975/214408680-70f0e9b1-3153-4525-a118-b3570c7597d7.mp4
)

### Steps to reproduce

1. Create a new draft on an entry with Neo blocks and Save
2. Switch to the Current Version, make a change, and Save
3. Switch back to the draft you created (a banner will say 'recent changes to the current version have been merged into this draft')
4. Blocks are scrambled

### Neo version

3.5.14

### Craft CMS version

4.3.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment] 2023-01-25 01:41
This seems to specifically affect blocks that have an empty Typed Link Field, so I'm going to consider this a duplicate of #631, which is itself caused by a Typed Link Field bug https://github.com/sebastian-lenz/craft-linkfield/issues/233. Happy to reopen this issue once that's fixed, if it turns out not to fix this issue.

**Closed by ttempleton** 2023-01-25 01:41 UTC
Labels: bug

**Comment by gateszies** [comment] 2023-06-20 17:53
@ttempleton We've done some further testing and this issue is occurring even when there is no Typed Link field present. Below is an updated screenshot displaying this behavior.

https://github.com/spicywebau/craft-neo/assets/66807975/be0f382f-43e7-424b-aba3-1e44f75bcbc7

**Steps to reproduce**
- Create a draft and edit a Neo block on that draft. Save draft.
- Go to the Current version and edit that same Neo block on the current. Save current.
- Go back to the draft you created. Block order is scrambled.

You can see in the screen recording that the block **Group Heading** has moved to the top of the page instead of its original location as the second block on the page. This scrambling becomes more severe with Neo blocks that contain children (the children are moved completely out of their parent). Again, this is on blocks that do not contain any Typed Link fields. 

Let me know if any other information is helpful - I'm happy to send along a database backup.

**Comment by ttempleton** [comment] 2023-06-21 04:13
Unable to reproduce that, but it would be a separate bug given this issue was directly related to nested Typed Link Fields (which might have turned out to be a Craft bug https://github.com/craftcms/cms/issues/12858 although I haven't tested to see if it was fixed for Neo).

There was a similar-sounding bug that was fixed in Neo 3.7.10, though. If you're already using 3.7.10+, or if you update and it still happens, please feel free to open a new issue.

**Comment by gateszies** [comment] 2023-06-29 21:16
Just updated to the latest version of Neo and Craft and this bug appears to be fixed. Thanks for the help!
