### ISSUE TITLE
Max Blocks on a child block issue

### ISSUE THREAD

**Issue by 23d1** [spicywebau/craft-neo#106] opened 2017-07-06 07:18 UTC
Setting the Max Blocks on a child block causes that block to not be accessible on any other item on the page once it's been used anywhere, within another nested sibling block.

Example; 
Row Block > Image Block > Overlay Block (this one has Max Blocks set to 1).
Then add another;
Row Block > Slideshow Block > Overlay Block is now grayed out.

Is this a bug or a feature, and would it make sense to remove it if it's a feature? I vote yes. ;)

**Comment by Emkaytoo** [comment] 2017-07-07 13:38
To call this a *feature* would be wrong, but it is the expected behavior. See #40 or #42 for some more detailed information.

**Comment by 23d1** [comment] 2017-07-07 18:48
Gotcha. Wouldn't it then make sense to just have a switch next to it along the lines of "Set Max Blocks across all parent blocks"? The wording could use some work, of course. Feels convoluted to have to solve that with a matrix field, no?

**Comment by benjamminf** [comment] 2017-07-27 02:06
I agree, and I think I've covered this in the other issue reports, that the Max Blocks option needs to work the way you describe. Unfortunately it's not too easy to change this behaviour, as it'll break sites that rely on this behaviour (I know we rely on this behaviour on most of our sites).

What I'm going to do is add a new setting "Max Top Blocks", which should be out in the next release the weekend.

**Comment by 23d1** [comment] 2017-07-28 18:49
Just to clarify "Max Top Blocks"; that would then be "Max of This Block under Parent Block"? :)

**Comment by 23d1** [comment] 2017-09-02 02:36
Just bumping, sorry. :) Any progress?

**Comment by ShaneHowell** [comment] 2017-09-29 16:22
Bumping this as well. Any update? 

Currently running into the same (or along the same line) issue where the top-level `Max Blocks` option prevents multiple `Child Blocks` from being added.

Example: setting `Max Blocks` to 1 and allowing child blocks with your `Block Type`, you won't be able to add any because the `Max Blocks` limit cascades down and ignores the individual settings.
![Screenshot](https://user-images.githubusercontent.com/5295741/31025198-a3056d88-a50f-11e7-9658-c3ba5782986d.png)

^ prevents you from adding child blocks:
![screenshot](https://user-images.githubusercontent.com/5295741/31025473-c5f9b1e0-a510-11e7-97b6-090f3688d9dd.png)

**Comment by jsunsawyer** [comment] 2018-12-07 01:13
I think that child blocks should be able to be limited based on the number of uses within a parent block.

This would keep the UI consistent for users. Dropdown options change between NEO and matrix fields, making it so users can't utilize the copy, paste, and clone features.

Also, the use of matrix fields doesn't even handle the desired limitations of fields, while maintaining re-ordering, for certain situations. With a matrix, you can only limit by the number of total blocks, not each individual block. To me, that's one of the features that NEO has over matrix and super table.

While I understand that changing the current max blocks limit functionality would break sites, I don't understand why an additional field or settings option would be uncalled for. If we could just flip a switch to change the logic of max-blocks, or even have both options, we'd have exactly what we want and expect.

**Comment by r0skar** [comment] 2020-05-09 11:10
Hi! First of all thanks for your work on this plugin. Its awesome. I was wondering if you are still considering adding this feature? Or is there workaround?

**Comment by pvldigital** [comment] 2020-05-10 23:05
Hi @r0skar,

Can't be certain when it will be released but it is on my TODO list.

**Comment by r0skar** [comment] 2020-05-11 08:04
That's great news! Let us know if there is anything we can help you with :+1:

**Comment by ttempleton** [comment] 2020-07-22 13:59
This is coming to Neo 2.8, the setting is currently planned to be named 'Max Sibling Blocks of This Type'.  It will apply to blocks within a parent block, as this issue describes, but it will also apply at the top level.

**Closed by ttempleton** 2020-07-22 13:59 UTC
Labels: improvement
