### ISSUE TITLE
Plugin Compatibility

### ISSUE THREAD

**Issue by ncc-jwood** [spicywebau/craft-neo#119] opened 2017-11-23 13:46 UTC
Your Neo plugin does not seem to be compatible with the newest version of Solspace's Calendar plugin.  With both plugins at the latest version and the calender using a Neo field, the calendar dies and throws an error when trying trying to create an event.

**Comment by steveooo9** [comment] 2017-11-26 22:22
Same here.

**Comment by ttempleton** [comment] 2020-06-07 14:48
I don't have a Solspace Calendar license to test compatibility on Craft 2 (given that there is no way to trial the Craft 2 version of Calendar) but the timing of this issue report suggests that, if the error was caused by Neo, it was probably related to the issues with Neo 1.5.0 that were fixed in later 1.5.x releases.

In any case, the Craft 2 versions of both plugins are out-of-date at this point, and the latest versions of Neo and Calendar for Craft 3 seem to work well together, so this issue can be closed now.

**Closed by ttempleton** 2020-06-07 14:48 UTC
